'use strict';
const R=ChatRenderer,e=R.esc,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',chat:'M4 4h16v12H9l-5 4V4Z M8 8h8M8 12h5',contacts:'M16 20v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6M17 4a3 3 0 0 1 0 6M22 20v-2a4 4 0 0 0-3-3.87',export:'M12 3v12m-4-4 4 4 4-4M4 15v5h16v-5',report:'M4 20V4m0 16h17M9 16v-5m5 5V7m5 9V3',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6',lock:'M6 10h12v10H6ZM8 10V7a4 4 0 0 1 8 0v3M12 14v2',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',arrow:'M5 12h14m-5-5 5 5-5 5',refresh:'M20 7v5h-5M4 17v-5h5M5.2 7a8 8 0 0 1 13-2l1.8 2M4 17l1.8 2a8 8 0 0 0 13-2',check:'m5 12 4 4L19 6',close:'m6 6 12 12M6 18 18 6',folder:'M3 6h7l2 2h9v12H3ZM3 6V4h7l2 2',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 5v5l3 2',calendar:'M5 5h14v16H5ZM8 3v4m8-4v4M5 10h14',chevron:'m9 6 6 6-6 6',file:'M5 3h9l5 5v13H5ZM14 3v6h5M8 13h8m-8 4h5',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18m0 8v6m0-10v1',wifi:'M2 8a16 16 0 0 1 20 0M5 12a11 11 0 0 1 14 0m-11 4a6 6 0 0 1 8 0m-4 4h.01',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3ZM20 2v4m-2-2h4',eye:'M2 12s3-7 10-7 10 7 10 7-3 7-10 7S2 12 2 12Zm10-3a3 3 0 1 0 0 6 3 3 0 0 0 0-6',chevrondown:'m6 9 6 6 6-6',qr:'M3 3h6v6H3ZM15 3h6v6h-6ZM3 15h6v6H3ZM15 15h2v2h-2ZM20 15v6h-5m-3-9h9M12 3v6M3 12h6',play:'m8 5 11 7-11 7Z',copy:'M8 8h12v13H8ZM4 16H3V3h12v1',logout:'M9 4H4v16h5m5-13 5 5-5 5m-6-5h11'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.file}"></path></svg>`;
const btn=(label,action,kind='',ico='',extra='')=>`<button class="btn ${kind}" data-action="${action}" ${extra}>${ico?icon(ico):''}${label}</button>`;
const num=n=>Number(n||0).toLocaleString();
const day=ts=>ts?new Date(ts*1000).toLocaleDateString('zh-CN',{month:'2-digit',day:'2-digit'}).replaceAll('/','.'):'—';
const dateFull=ts=>ts?new Date(ts*1000).toLocaleDateString('zh-CN').replaceAll('/','.'): '尚未归档';
let state=null,stats=null,route='home',currentChat=null,chats=[],allChats=[],messages=[],messageOffset=0,chatKind='all',chatQuery='',messageQuery='',messageUntil='',messageKind='',hasMore=false,contactsPage=0,contactsQuery='',contactSelection=new Set(),exportSelection=new Set(),exportAll=true,exportFormats=new Set(['html']),reportJob=null,selectedJob=null,modalType='',native=null,toastTimer,queryTimer,requestSequence=0,listSequence=0;
let modelProfiles={};
let insightReport=null,insightCid='',proactiveDrafts=[],proactiveSnapshot='';
const navs=[['home','home','首页'],['chat','chat','聊天记录'],['contacts','contacts','联系人'],['media','file','媒体管理'],['automation','chat','自动回复'],['proactive','clock','主动消息'],['model','spark','AI 模型'],['insights','spark','关系镜像'],['memory','file','聊天记忆'],['coach','spark','表达练习'],['moments','eye','朋友圈'],['articles','file','公众号文章'],['export','export','导出中心'],['report','report','年度回顾'],['antirevoke','lock','防撤回'],['multi','contacts','微信多开']];
const account=()=>state?.accounts.find(a=>a.id===state.selected);
const asset=p=>`/media/${state.selected}/${p.split('/').map(encodeURIComponent).join('/')}`;
const avatar=(name,path='',extra='')=>!path&&extra==='group-avatar'?`<span class="avatar group-avatar" title="微信原始群头像尚未缓存">${icon('contacts')}</span>`:R.avatar(name,path?asset(path):'',extra);
async function api(path,body){const response=await fetch(path,{headers:body?{'Content-Type':'application/json'}:{},method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.remove('hidden');toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4500);}
function heading(title,subtitle,actions=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;}
function empty(title,description,action='sync',label='同步聊天记录',ico='chat'){return `<div class="empty-state"><span class="empty-icon">${icon(ico)}</span><h2>${title}</h2><p>${description}</p>${action?btn(label,action,'primary',action==='detect'?'refresh':'arrow'):''}</div>`;}
function needArchive(){return `<div class="page">${heading(navs.find(n=>n[0]===route)?.[2]||'我的归档','浏览和管理当前账号的本地数据。')}${empty('尚未同步聊天记录','同步当前账号后，即可浏览聊天、导出文件和制作年度回顾。')}${account()?.legacy?`<div style="text-align:center">${btn('导入已有的 TXT 归档','legacy','ghost','folder')}</div>`:''}</div>`;}
function renderShell(){
 $('#navigation').innerHTML=navs.map(([id,ico,label])=>`<button class="nav-item ${route===id?'active':''}" data-nav="${id}">${icon(ico)}<span>${label}</span>${id==='report'?'<span class="badge">YEAR</span>':''}</button>`).join('');
 $('#quit-app').innerHTML=icon('logout')+'<span>退出软件</span>';
 $('#settings-nav').innerHTML=icon('settings')+'<span>设置</span>';$('#settings-nav').classList.toggle('active',route==='settings');
 $('#privacy-label').innerHTML=icon('lock')+'本地数据';$('#task-icon').innerHTML=icon('clock');$('#demo-label').classList.toggle('hidden',!state?.demo);
 const a=account();$('#sidebar-account').innerHTML=avatar(a?.display_name||'拾')+`<span>${e(a?.display_name||'尚未登录微信')}<small>${a?.active?'已识别 · 当前登录账号':a?'离线归档 · 可随时浏览':'登录后将自动识别'}</small></span>`;
 $('#top-avatar').textContent=R.initials(a?.display_name||'拾');$('#page-name').textContent=navs.find(n=>n[0]===route)?.[2]||'设置';
}
async function loadState(){state=await api('/api/state');reportJob=state.jobs.filter(j=>j.kind==='report'&&j.status==='done'&&j.account_id===state.selected).at(-1)||null;stats=null;if(account()?.has_archive){try{stats=await api('/api/stats');}catch(err){toast(err.message);}}renderShell();}
async function navigate(next){route=navs.some(n=>n[0]===next)||next==='settings'?next:'home';location.hash=route;renderShell();requestSequence++;$('#content').classList.toggle('chat-content',route==='chat');
 if(['chat','contacts','export','report','moments','automation','proactive','model','media'].includes(route)&&!stats){$('#content').innerHTML=needArchive();return;}
 if(route==='home')await renderHome();else if(route==='chat')await renderChat();else if(route==='contacts')await renderContacts();else if(route==='media')await renderMedia();else if(route==='automation')await renderAutomation();else if(route==='proactive')await renderProactive();else if(route==='model')await renderModel();else if(route==='insights')await renderInsights();else if(route==='memory'||route==='coach')await PersonalUI.render(route);else if(route==='articles')await ArticlesUI.render();else if(route==='export')await renderExport();else if(route==='report')await renderReport();else if(route==='moments')await renderMoments();else if(route==='antirevoke')await renderAntiRevoke();else if(route==='multi')await renderMulti();else {renderSettings();await StorageUI.render();}
}
function statCard(label,value,unit,ico,foot){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon">${icon(ico)}</span></div><div class="stat-value">${value}<span>${unit}</span></div><div class="stat-foot">${foot}</div></div>`;}
async function renderHome(){
 const a=account(),s=stats;
 const updated=s?(s.metadata.updated_at||'').replace('T',' ').slice(0,16):'';
 $('#content').innerHTML=`<div class="page home-page">
 ${heading('我的微信档案','浏览聊天、导出记录，或查看年度统计。',btn('重新检测账号','detect','ghost','refresh'))}
 <section class="account-focus" aria-label="当前微信账号">
  <div class="account-focus-main"><div class="account-eyebrow">当前账号 <span class="pill ${a?.active?'':'offline'}">${a?.active?'微信已登录':a?'离线归档':'未识别'}</span></div>
   <div class="account-focus-identity">${avatar(a?.display_name||'微信', '', 'account-avatar')}<div><h2>${e(a?.display_name||'请先登录电脑微信')}</h2><p>${e(a?.username||'登录后点击右上角重新检测账号')}</p></div></div>
   <div class="account-focus-actions">${s?btn('打开聊天记录','go-chat','primary','chat'):a?.active?btn('同步聊天记录','sync','primary','refresh'):btn('检测微信账号','detect','primary','refresh')}${s?btn('同步更新','sync','','refresh'):''}${a?btn('切换账号','accounts','ghost','chevrondown'):''}</div>
  </div>
  <div class="archive-summary"><span class="summary-label">${s?'本地归档已就绪':'首次使用'}</span><strong>${s?num(s.messages)+' 条消息':'先同步，再浏览'}</strong><p>${s?'最近同步：'+e(updated||'时间未知'):'同步会读取当前账号的聊天记录，并整理本机媒体。'}</p>${s?`<p>记录范围：${dateFull(s.first_ts)} — ${dateFull(s.last_ts)}</p>`:''}${!s&&a?.legacy?btn('导入已有 TXT 归档','legacy','small','folder'):''}</div>
 </section>
 <div class="stat-grid overview-stats">${statCard('聊天会话',s?num(s.conversations):'—','个','chat','单聊、群聊与公众号')}${statCard('微信好友',s?num(s.contacts):'—','位','contacts','当前账号通讯录中的好友')}${statCard('有记录的日子',s?num(s.days):'—','天','calendar','按实际聊天日期统计')}${statCard('可查看年份',s?num(s.years.length):'—','年','report',s?s.years.slice().reverse().join(' / '):'同步后显示')}</div>
 <div class="home-columns"><section class="recent-section"><div class="section-heading"><h2>最近会话</h2><button data-nav="chat">全部聊天 ${icon('chevron')}</button></div><div id="recent-chats" class="recent-list">${s?'<div class="skeleton"></div>':'<div class="empty-inline">同步完成后，这里会显示最近的会话。</div>'}</div></section>
 <aside class="home-tools"><div class="section-heading"><h2>档案工具</h2></div><div class="tool-list"><button class="tool-row" data-nav="export"><span class="tool-icon">${icon('export')}</span><span><b>导出聊天记录</b><small>选择会话、日期和文件格式</small></span>${icon('chevron')}</button><button class="tool-row" data-nav="contacts"><span class="tool-icon">${icon('contacts')}</span><span><b>联系人</b><small>查找资料，导出通讯录</small></span>${icon('chevron')}</button><button class="tool-row" data-nav="report"><span class="tool-icon">${icon('report')}</span><span><b>年度回顾</b><small>个人或双人聊天统计</small></span>${icon('chevron')}</button></div><div class="local-summary">${icon('lock')}<div><b>数据保存在本机</b><p>聊天浏览和导出均在本地完成。</p></div></div></aside></div>
 </div>`;
 if(s){const id=state.selected;const data=await api('/api/conversations?limit=6');if(route==='home'&&id===state.selected)$('#recent-chats').innerHTML=data.items.map(c=>`<button class="recent-card" data-chat="${e(c.id)}">${avatar(c.title,c.avatar,c.kind==='group'?'group-avatar':'')}<div class="recent-copy"><b>${e(c.title)}</b><p>${e(c.preview||'打开聊天记录')}</p></div><span class="recent-meta"><time>${day(c.last_ts)}</time><small>${num(c.total)} 条</small></span>${icon('chevron')}</button>`).join('')||'<div class="empty-inline">暂时没有可显示的会话。</div>';}
}
async function renderChat(){
 $('#content').innerHTML=`<div class="chat-layout"><aside class="conversation-panel"><div class="conversation-top"><div class="conversation-title"><h1>聊天记录</h1><span>${num(stats.conversations)} 段对话</span></div><div class="search-box">${icon('search')}<input id="chat-search" placeholder="搜索联系人或群聊" value="${e(chatQuery)}" aria-label="搜索联系人或群聊"></div><div class="tabs">${[['all','全部'],['direct','单聊'],['group','群聊'],['official','公众号']].map(([id,label])=>`<button class="tab ${chatKind===id?'active':''}" data-chat-kind="${id}">${label}</button>`).join('')}</div></div><div class="conversation-list" id="conversation-list"></div><div class="pagination" id="chat-pagination"></div></aside><section class="chat-pane" id="chat-pane"><div class="conversation-empty">${empty('选择一个会话','在左侧选择联系人或群聊，查看聊天记录。','')}</div></section></div>`;
 await loadConversations();if(currentChat)await openChat(currentChat.id);
}
async function loadConversations(offset=0){const sequence=++listSequence;const data=await api('/api/conversations?'+new URLSearchParams({q:chatQuery,kind:chatKind,offset,limit:100}));if(route!=='chat'||sequence!==listSequence)return;if(!offset)chats=[];chats.push(...data.items);$('#conversation-list').innerHTML=chats.map(c=>`<button class="conversation ${currentChat?.id===c.id?'active':''}" data-chat="${e(c.id)}">${avatar(c.title,c.avatar,c.kind==='group'?'group-avatar':'')}<div class="conversation-body"><div class="conversation-head"><b>${e(c.title)}</b><time>${day(c.last_ts)}</time></div><p>${e(c.preview||'打开聊天记录')}</p></div></button>`).join('')||'<div class="empty-inline">没有找到会话</div>';$('#chat-pagination').innerHTML=chats.length<data.total?btn('加载更多会话','more-chats','ghost small'): `<span>共 ${num(data.total)} 段对话</span>`;}
async function getAllChats(){if(!allChats.length){const data=await api('/api/conversations?limit=5000');allChats=data.items;}return allChats;}
async function openChat(cid){if(route!=='chat'){await getAllChats();currentChat=allChats.find(c=>c.id===cid)||chats.find(c=>c.id===cid);await navigate('chat');return;}let c=chats.find(c=>c.id===cid)||allChats.find(c=>c.id===cid);if(!c){await getAllChats();c=allChats.find(c=>c.id===cid);}if(!c)return;currentChat=c;messageOffset=0;messages=[];messageQuery='';messageUntil='';messageKind='';$$('.conversation').forEach(n=>n.classList.toggle('active',n.dataset.chat===cid));
 $('#chat-pane').innerHTML=`<header class="chat-head"><div><h2>${e(c.title)}</h2><p>${c.kind==='group'?'群聊':c.kind==='official'?'公众号':'好友'} · ${num(c.total)} 条消息 · ${e(c.id)}</p></div><div class="chat-tools">${btn('补全表情','restore-chat-emoji','small','refresh')}${btn('导出这段对话','export-chat','small','export')}</div></header><div class="chat-search"><div class="search-box">${icon('search')}<input id="message-search" placeholder="搜索这段对话" aria-label="搜索这段对话"></div><select id="message-kind" aria-label="筛选消息类型"><option value="">全部类型</option>${Object.entries(R.names).map(([id,title])=>`<option value="${id}">${title}</option>`).join('')}</select><input id="message-date" type="date" aria-label="跳转到日期">${btn('跳转','jump-date','small')}<button class="icon-button" data-action="reset-messages" title="返回最新消息" aria-label="返回最新消息">${icon('refresh')}</button></div><div class="messages-container" id="messages"><div class="loading-screen"><span class="spinner"></span></div></div><div class="chat-compose"><textarea id="chat-compose-text" rows="2" maxlength="2000" placeholder="给 ${e(c.title)} 发消息 · Ctrl+Enter 发送" aria-label="发送消息内容"></textarea>${c.kind==='direct'?btn('原生语音','voice-modal','','play'):''}${btn('发送','send-chat','primary','arrow')}</div><div class="reader-notice">${stats.metadata.source==='legacy_txt'?'当前为旧 TXT 归档，媒体和原消息编号需重新同步数据库。':'发送通过当前微信界面完成，结果以微信窗口和同步记录为准。'}</div>`;
 Mirror.attachComposer(c);
 await loadMessages();
}
async function loadMessages(older=false,serverId=''){
 if(!currentChat)return;const sequence=++requestSequence,cid=currentChat.id;
 const data=await api('/api/messages?'+new URLSearchParams({cid,q:messageQuery,offset:older?messageOffset:0,until:messageUntil,kind:messageKind,server_id:serverId}));
 if(route!=='chat'||cid!==currentChat?.id||sequence!==requestSequence)return;if(data.not_found){toast('引用的原消息未包含在本地归档中。');return;}
 const container=$('#messages'),previousHeight=container.scrollHeight,previousTop=container.scrollTop;
 messages=older?[...data.items,...messages]:data.items;messageOffset=data.offset;hasMore=data.has_more;
 container.innerHTML=(hasMore?'<button class="load-older" data-action="older">查看更早的消息 ↑</button>':'<div class="date-separator">已显示最早的记录</div>')+(messages.length?R.list(messages,asset):'<div class="empty-inline">没有找到符合条件的消息</div>');
 if(older)container.scrollTo({top:container.scrollHeight-previousHeight+previousTop,behavior:'instant'});else if(!serverId){container.scrollTo({top:container.scrollHeight,behavior:'instant'});let pinned=true;container.addEventListener('wheel',()=>pinned=false,{once:true});container.querySelectorAll('img').forEach(img=>img.addEventListener('load',()=>{if(pinned&&sequence===requestSequence)container.scrollTo({top:container.scrollHeight,behavior:'instant'});},{once:true}));}
 ensureVisibleEmoji();
 if(serverId){const item=messages.find(m=>m.server_id===serverId),node=item?$('#msg-'+item.id):null;node?.scrollIntoView({block:'center'});node?.classList.add('reference-highlight');}
}
const emojiRequested=new Set();
async function ensureVisibleEmoji(){if(!state?.settings.auto_emoji||route!=='chat')return;const ids=messages.filter(m=>m.kind==='emoji'&&!m.media_path&&!emojiRequested.has(state.selected+':'+m.id)).slice(-30).map(m=>m.id);if(!ids.length)return;try{const j=await api('/api/emoji/ensure',{ids});ids.forEach(id=>emojiRequested.add(state.selected+':'+id));if(j.id&&!state.jobs.some(x=>x.id===j.id))state.jobs.push({...j,status:'running'});}catch{}}
async function refreshEmoji(){if(route!=='chat')return;const ids=messages.filter(m=>m.kind==='emoji').map(m=>m.id);if(!ids.length)return;const cid=currentChat?.id,data=await api('/api/emoji/status?'+new URLSearchParams({ids:ids.slice(-100).join(',')}));if(route!=='chat'||currentChat?.id!==cid)return;const box=$('#messages'),top=box.scrollTop,bottom=box.scrollHeight-top-box.clientHeight<100;for(const update of data.items){const m=messages.find(x=>x.id===update.id);if(!m||(m.media_path===update.media_path&&m.media_status===update.media_status))continue;Object.assign(m,update);const node=$('#msg-'+m.id);if(node)node.outerHTML=R.message(m,asset);}const pin=()=>box.scrollTop=bottom?box.scrollHeight:top;pin();box.querySelectorAll('img').forEach(img=>img.addEventListener('load',pin,{once:true}));}
async function renderContacts(){
 $('#content').innerHTML=`<div class="page">${heading('联系人','仅显示当前账号通讯录中的微信好友；群聊参与者仍用于聊天署名与头像。',btn('导出联系人','export-contacts','primary','export'))}<div class="filter-row"><div class="search-box">${icon('search')}<input id="contact-search" placeholder="搜索昵称、备注或微信号" value="${e(contactsQuery)}" aria-label="搜索联系人"></div><span class="muted" id="contact-count"></span></div><div class="table-wrap"><table><thead><tr><th style="width:40px"><input id="contact-all" type="checkbox" aria-label="选择当前页联系人"></th><th>联系人</th><th>备注</th><th>微信号 / ID</th><th>类型</th></tr></thead><tbody id="contact-rows"></tbody></table></div><div class="pagination" id="contact-pagination"></div></div>`;await loadContacts();
}
let contactRows=[];
async function loadContacts(){const sequence=++requestSequence;const data=await api('/api/contacts?'+new URLSearchParams({q:contactsQuery,offset:contactsPage*40,limit:40}));if(route!=='contacts'||sequence!==requestSequence)return;contactRows=data.items;$('#contact-count').textContent=`共 ${num(data.total)} 位联系人${contactSelection.size?' · 已选 '+contactSelection.size+' 位':''}`;$('#contact-rows').innerHTML=data.items.map(c=>`<tr><td><input type="checkbox" data-contact="${e(c.username)}" ${contactSelection.has(c.username)?'checked':''} aria-label="选择${e(c.nickname||c.username)}"></td><td><div class="contact-name">${avatar(c.nickname||c.username,c.avatar)}<span>${e(c.nickname||c.username)}</span></div></td><td>${e(c.remark||'—')}</td><td title="${e(c.username)}">${e(c.alias||c.username)}</td><td><span class="pill ${c.kind==='direct'?'':'offline'}">${{direct:'个人联系人',group:'群聊',official:'公众号'}[c.kind]||'联系人'}</span></td></tr>`).join('')||'<tr><td colspan="5" style="text-align:center;padding:50px">没有找到联系人</td></tr>';$('#contact-pagination').innerHTML=`<span>第 ${data.total?contactsPage+1:0} / ${Math.ceil(data.total/40)} 页</span>${btn('上一页','contacts-prev','small','',''+(contactsPage?'':'disabled'))}${btn('下一页','contacts-next','small','',((contactsPage+1)*40<data.total?'':'disabled'))}`;}
const formatInfo=[['html','HTML','还原聊天，交互浏览'],['docx','Word','便于整理与打印'],['txt','TXT','轻量纯文本归档'],['csv','CSV','方便检索与分析'],['sqlite','SQLite','完整结构化消息'],['emoji','表情包','原文件与可点击图库'],['contacts','联系人','独立通讯录 CSV']];
async function renderExport(){await getAllChats();$('#content').innerHTML=`<div class="page">${heading('导出中心','选择格式、时间范围和会话，将聊天记录保存到本机。')}<div class="export-grid"><div><section class="panel export-panel"><h2 class="step-heading"><i>1</i> 选择导出格式</h2><div class="format-grid">${formatInfo.map(([id,label,desc])=>`<label class="format-card ${exportFormats.has(id)?'selected':''}"><input type="checkbox" data-format="${id}" ${exportFormats.has(id)?'checked':''}><span class="format-symbol">${id==='contacts'?'ID':id.toUpperCase().slice(0,4)}</span><b>${label}</b><small>${desc}</small></label>`).join('')}</div></section><section class="panel export-panel"><h2 class="step-heading"><i>2</i> 选择时间范围</h2><div class="date-fields"><input type="date" id="export-start" aria-label="导出起始日期"><span>至</span><input type="date" id="export-end" aria-label="导出结束日期"></div><p class="path-label">不选日期则导出全部时间；结束日期包含当天。</p><label class="export-options"><input type="checkbox" id="export-media" checked><span>包含已恢复的图片、语音、视频与文件<small>同时保存媒体和可点击浏览的 HTML 阅读器。请保留整个导出文件夹；缺失附件会注明。</small></span></label></section><section class="panel export-panel"><h2 class="step-heading"><i>3</i> 选择保存位置</h2><div class="setting-path"><input id="export-path" value="${e(state.settings.output_dir)}" aria-label="导出目录">${btn('选择文件夹','browse-output','','folder')}</div><p class="path-label">每次导出会新建独立文件夹，不覆盖此前的归档。</p></section></div><aside><section class="panel"><div class="section-heading"><h2>选择聊天</h2><span class="muted">${num(stats.conversations)} 段</span></div><div class="search-box">${icon('search')}<input id="export-search" placeholder="搜索会话" aria-label="搜索要导出的会话"></div><label class="selection-controls"><input type="checkbox" id="export-all" ${exportAll?'checked':''}>全部会话</label><div class="selection-list" id="export-conversations"></div><div class="export-summary" id="export-summary"></div>${btn('开始导出','start-export','primary export-submit','export')}</section></aside></div><section class="history-list"><div class="section-heading"><h2>最近导出记录</h2></div><div id="export-history"></div></section></div>`;renderExportChoices();renderHistory();}
function renderExportChoices(q=''){if(!$('#export-conversations'))return;$('#export-conversations').innerHTML=allChats.filter(c=>(c.title+c.id).toLowerCase().includes(q.toLowerCase())).map(c=>`<label class="selection-row"><input type="checkbox" data-export-chat="${e(c.id)}" ${exportAll||exportSelection.has(c.id)?'checked':''}>${avatar(c.title)}<span>${e(c.title)}</span></label>`).join('')||'<div class="empty-inline">没有匹配的会话</div>';exportSummary();}
function exportSummary(){if($('#export-summary'))$('#export-summary').innerHTML=`已选择 <b>${exportAll?num(stats.conversations):exportSelection.size}</b> 段对话<br>导出为 <b>${[...exportFormats].map(f=>formatInfo.find(x=>x[0]===f)?.[1]).join('、')||'尚未选择格式'}</b>`;}
function renderHistory(){if(!$('#export-history'))return;const jobs=state.jobs.filter(j=>j.kind==='export'&&j.account_id===state.selected).reverse();$('#export-history').innerHTML=jobs.map(j=>`<div class="history-row">${icon(j.status==='done'?'check':'clock')}<div><b>${j.status==='done'?'导出已完成':j.status==='error'?'导出失败':j.status==='cancelled'?'导出已取消':'正在导出'}</b><p>${e(j.result?.path||j.message)}</p></div>${btn(j.status==='done'?'打开文件夹':'查看详情',j.status==='done'?'open-job':'job-detail','small','',`data-job="${j.id}"`)}</div>`).join('')||'<div class="empty-inline">导出完成后，可以从这里打开保存的文件。</div>';}
async function renderReport(){await getAllChats();const years=stats.years,latest=reportJob?.result?.report?.year||years[0]||new Date().getFullYear();$('#content').innerHTML=`<div class="page">${heading('年度回顾','按年份查看消息统计，生成个人或双人报告。')}<div class="report-intro"><div><div class="eyebrow">A YEAR WORTH REMEMBERING</div><h2>选择年份与回顾范围</h2><p>统计消息、字数、连续聊天与常用词。<br>同时生成 HTML 与高清 PNG 图片。</p></div><div class="year-art"><span>${latest}</span></div></div><div class="report-controls"><label class="field-label">选择年份<select id="report-year">${years.map(y=>`<option value="${y}" ${y===latest?'selected':''}>${y} 年</option>`).join('')}</select></label><label class="field-label wide">回顾范围<select id="report-contact"><option value="">个人年度回顾 · 全部对话</option>${allChats.filter(c=>c.kind==='direct').map(c=>`<option value="${e(c.id)}">双人回顾 · 我和${e(c.title)}</option>`).join('')}</select></label>${btn('生成年度回顾','generate-report','primary','spark',years.length?'':'disabled')}</div><div id="report-output">${reportJob&&reportJob.account_id===state.selected&&reportJob.result?reportPreview(reportJob):'<div class="report-placeholder"><div class="notebook-mark">✳</div><h3>尚未生成年度报告</h3><p>真实消息统计 · 活跃日历 · 高频词 · 双人互动 · 手机扫码查看</p></div>'}</div></div>`;}
function reportPreview(job){const d=job.result.report,max=Math.max(...d.months,1);return `<div class="stat-grid">${statCard('这一年说过',num(d.total),'句话','chat','来自实际归档消息')}${statCard('文字总量',num(d.characters),'字','file','非空白字符，含标点')}${statCard('收到回应',num(d.received),'条','chat','来自世界的回响')}${statCard('有对话的日子',num(d.days),'天','calendar','平凡日子里的热闹')}</div><div class="report-results"><div class="panel"><div class="section-heading"><h2>十二个月的对话</h2><span class="muted">${d.year}</span></div><div class="mini-bars">${d.months.map((n,i)=>`<div class="mini-col"><i style="height:${Math.max(2,115*n/max)}px" title="${i+1}月 · ${num(n)} 条"></i><small>${String(i+1).padStart(2,'0')}</small></div>`).join('')}</div></div><div class="panel"><div class="section-heading"><h2>常挂在嘴边的话</h2></div><div class="report-words">${d.words.slice(0,18).map((w,i)=>`<span style="font-size:${11+Math.sqrt(w.count/(d.words[0]?.count||1))*13}px" title="出现 ${num(w.count)} 次">${e(w.word)}</span>`).join('')||'<p class="muted">文本不足以生成高频词</p>'}</div></div></div><div class="report-actions">${job.result.image?btn('打开年报图片','open-report-image','','file',`data-job="${job.id}"`):''}${btn('打开完整年报','open-report','','eye',`data-job="${job.id}"`)}${btn('手机扫码查看','share-report','primary','qr',`data-job="${job.id}"`)}</div>`;}
function renderSettings(){const s=state.settings;$('#content').innerHTML=`<div class="page">${heading('设置','管理保存位置、微信连接与媒体恢复。',btn('保存设置','save-settings','primary','check'))}<section class="panel settings-section"><h2>本地保存</h2><div class="setting-row"><div><label for="settings-auto-emoji">浏览时自动补全表情</label><p>仅访问消息自带的微信表情下载地址，成功后保存本地；动态表情保留动画。</p></div><input type="checkbox" class="switch" id="settings-auto-emoji" ${s.auto_emoji?'checked':''}></div><div class="setting-row stack"><label for="settings-output">默认导出目录</label><p>聊天文档与年度回顾会保存在这里，每次导出新建一个文件夹。</p><div class="setting-path"><input id="settings-output" value="${e(s.output_dir)}">${btn('选择文件夹','browse-output','','folder')}</div></div><div class="setting-row"><div><label for="settings-media">同步时恢复本地媒体</label><p>读取本机已保存的图片、视频、语音与附件；首次同步可能需要更多时间。</p></div><input type="checkbox" class="switch" id="settings-media" ${s.include_media?'checked':''}></div><div class="setting-row"><div><label>补全缺失的表情包</label><p>点击后联网访问微信表情 CDN，成功下载后保存在本机。失效链接无法恢复。</p></div>${btn('联网补全表情','restore-emoji','','refresh',account()?.has_archive?'':'disabled')}</div></section><section class="panel settings-section"><h2>微信连接</h2><div class="setting-row"><div><label for="settings-auto">自动增量更新</label><p>每秒轻量检查新消息，保留已有归档；媒体恢复在手动同步时进行。</p></div><input type="checkbox" class="switch" id="settings-auto" ${s.auto_sync?'checked':''}></div><div class="setting-row"><div><label>当前登录账号</label><p>${e(account()?.display_name||'尚未识别')} · ${account()?.active?'微信正在运行':'离线'}</p></div>${btn('重新检测','detect','','refresh')}</div><div class="setting-row stack"><label for="settings-root">微信数据目录（辅助查找）</label><p>通常自动从微信正在打开的数据库识别；自定义路径可以在这里记录。</p><div class="setting-path"><input id="settings-root" value="${e(s.data_root||account()?.root||'')}" placeholder="xwechat_files 所在目录">${btn('选择文件夹','browse-data','','folder')}</div></div><div class="setting-row"><div><label for="settings-keys">下次同步重新获取数据库密钥</label><p>微信升级、密钥失效或数据库验证失败时启用。需要微信保持登录。</p></div><input type="checkbox" class="switch" id="settings-keys" ${s.force_keys?'checked':''}></div></section><section class="panel settings-section"><h2>关于拾光</h2><div class="about-info">拾光 2.1 · Windows 微信 4.x 本地档案<br>支持聊天浏览、联系人、HTML / Word / TXT / CSV / SQLite 导出及个人、双人年度回顾。<br>支持本机媒体恢复；未下载、已删除、无法解码的附件会如实标注。WXGF 可解码时保存首帧。<br>功能设计参考 <a href="https://github.com/shixiaogaoya/MemoTrace" target="_blank" rel="noopener noreferrer">MemoTrace ↗</a>，继续使用原有 wxdump 数据库取钥能力。</div></section></div>`;}
function showModal(title,body,actions='',wide=false){modalType=modalType||'generic';$('#modal').innerHTML=`<div class="modal-card ${wide?'wide':''}"><div class="modal-top"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close-modal" aria-label="关闭弹窗">${icon('close')}</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}</div>`;$('#modal').classList.remove('hidden');$('#modal [data-action="close-modal"]')?.focus();}
function closeModal(){if(modalType==='share')api('/api/share/stop',{}).catch(()=>{});$('#modal').classList.add('hidden');modalType='';}
function accountsModal(){modalType='accounts';showModal('我的微信账号',`<p class="modal-description">当前登录账号来自微信正在打开的数据库。离线账号仅用于查看已有归档。</p>${state.accounts.map(a=>`<button class="account-option ${a.id===state.selected?'selected':''}" data-account-id="${a.id}">${avatar(a.display_name)}<div><b>${e(a.display_name)}</b><small>${e(a.username)}</small></div><span class="pill ${a.active?'':'offline'}">${a.active?'当前登录':'离线归档'}</span></button>`).join('')||'<div class="empty-inline">未发现账号。请先在电脑上登录微信。</div>'}`,btn('重新检测','detect','','refresh'));}
function jobModal(id){selectedJob=id;modalType='job';updateJobModal();}
function updateJobModal(){
 const j=state.jobs.find(x=>x.id===selectedJob);if(!j)return;
 const modal=$('#modal'),same=modal.dataset.jobId===j.id&&modal.dataset.jobStatus===j.status&&!!modal.querySelector('.task-log');
 const names={sync:'正在收藏你的微信时光',legacy:'导入已有的聊天归档',export:'把聊天保存到本地',report:'正在制作年度回顾',emoji:'正在联网补全表情',moments_sync:'正在同步朋友圈',moments_export:'正在导出朋友圈',moments_repair:'正在修复朋友圈半图'};
 if(!same){
  const opened=modal.querySelector('details')?.open;
  let actions=j.status==='running'?btn('取消任务','cancel-job','danger'):btn('完成','close-modal','primary');
  if(j.status==='done'&&j.result?.path)actions=btn('打开文件夹','open-job','','folder',`data-job="${j.id}"`)+actions;
  showModal(j.status==='done'?'任务已完成':j.status==='error'?'任务暂时未能完成':j.status==='cancelled'?'任务已取消':names[j.kind],`<p class="task-status"></p><div class="progress-track"><div class="progress-fill"></div></div><p class="path-label" data-job-progress></p><p class="path-label" data-job-media></p><p class="path-label" data-job-path></p><details ${opened?'open':''}><summary>查看处理日志</summary><pre class="task-log"></pre></details>`,actions);
  modal.dataset.jobId=j.id;modal.dataset.jobStatus=j.status;
 }
 modal.querySelector('.task-status').textContent=j.message||'';
 modal.querySelector('.progress-fill').style.width=`${j.percent}%`;
 modal.querySelector('[data-job-progress]').textContent=j.status==='running'?`已完成 ${j.percent}% · 可以继续浏览已有归档`:j.result?.messages?`共整理 ${num(j.result.messages)} 条消息`:'';
 modal.querySelector('[data-job-media]').textContent=j.result?.media?`媒体：可打开 ${num(j.result.media.available)} 个，缺失 ${num(j.result.media.missing)} 个。详情见导出目录中的媒体恢复情况.json。`:'';
 modal.querySelector('[data-job-path]').textContent=j.result?.path||'';
 const log=modal.querySelector('.task-log'),bottom=log.scrollHeight-log.scrollTop-log.clientHeight<30;
 const lines=(j.logs||[]).join('\n');if(log.textContent!==lines){log.textContent=lines;if(bottom)log.scrollTop=log.scrollHeight;}
}
async function startJob(kind,options={}){if(!account()){toast('请先登录微信，再点击重新检测。');return;}const job=await api('/api/jobs',{kind,options:{...options,account_id:state.selected}});state.jobs.push({...job,status:'running'});jobModal(job.id);renderTaskbar();}
async function runInsightSkill(node,kind,cid){const accountId=state.selected;node.disabled=true;const host=node.closest('.setting-path')||node.parentElement;let box=document.createElement('div');box.className='insight-skill-progress';box.setAttribute('role','status');box.setAttribute('aria-live','polite');box.innerHTML='<progress max="100" value="0"></progress> <span>正在读取聊天记录 · 0%</span>';host.after(box);const startedAt=Date.now();try{const task=await api('/api/insights/skill/start',{kind,cid});for(;;){if(state.selected!==accountId)throw Error('登录账号已变化，当前进度已结束。');const job=await api('/api/insights/skill/'+encodeURIComponent(task.id));const bar=box.querySelector('progress'),label=box.querySelector('span');if(bar)bar.value=job.percent||0;if(label)label.textContent=`${job.stage||'正在处理'} · ${job.percent||0}% · 已用 ${Math.floor((Date.now()-startedAt)/1000)} 秒`;if(job.status==='error')throw Error(job.error||'技能生成失败。');if(job.status==='done'){if(route==='insights'&&insightCid===cid){await loadInsightSkills(cid);toast(kind==='my_style'?'风格规则已生成，可修改后保存。':'成长支持规则已生成，可修改后保存。');}return job.result;}await new Promise(resolve=>setTimeout(resolve,700));}}finally{if(node.isConnected)node.disabled=false;setTimeout(()=>box.remove(),5000);}}
function renderTaskbar(){const j=state?.jobs.find(j=>j.status==='running'&&!j.automatic);$('#taskbar').classList.toggle('hidden',!j);if(j)$('#taskbar').innerHTML=`<span class="spinner"></span><div><b>${e(j.message)}</b><small>${j.percent}% · 在后台处理手动任务</small></div>${btn('查看进度','job-detail','small','',`data-job="${j.id}"`)}`;}
let polling=false;
async function poll(){if(polling||!state)return;polling=true;try{
 const previous=new Map(state.jobs.map(j=>[j.id,j.status])),oldLive=state.live||{},fresh=await api('/api/state');state=fresh;
 if(state.live?.chat_revision!==oldLive.chat_revision&&route==='chat'&&currentChat&&!messageQuery&&!messageUntil&&!messageKind){await loadConversations();const box=$('#messages'),bottom=box&&box.scrollHeight-box.scrollTop-box.clientHeight<100;if(bottom)await loadMessages();else{const notice=$('.reader-notice');if(notice)notice.innerHTML=btn('有更新，点击查看最新消息','reset-messages','small');}}
 if(state.live?.moments_revision!==oldLive.moments_revision&&route==='moments'){await loadMoments(0);}
 for(const j of state.jobs){if(j.status==='running'||previous.get(j.id)===j.status)continue;
  if(j.status==='done'){
   if(j.kind==='report'){reportJob=j;if(route==='report')$('#report-output').innerHTML=reportPreview(j);}
   if(j.kind==='emoji')await refreshEmoji();
   if(['sync','legacy','quick_sync'].includes(j.kind)&&(!j.automatic||j.result?.new_messages||j.result?.updated_messages)){
    allChats=[];stats=await api('/api/stats');renderShell();
    if(route==='chat'&&currentChat){if(!j.automatic)await loadConversations();const box=$('#messages'),bottom=box&&box.scrollHeight-box.scrollTop-box.clientHeight<100;
     if(bottom&&!messageQuery&&!messageUntil&&!messageKind&&!j.automatic)await loadMessages();
     else if((j.result?.new_messages||j.result?.updated_messages)&&(!j.automatic||!bottom||messageQuery||messageUntil||messageKind)){const notice=$('.reader-notice');if(notice)notice.innerHTML=btn('有更新，点击查看最新消息','reset-messages','small');}
    }else if(!j.automatic)await navigate(route);
   }
   if(['moments_sync','moments_quick','moments_repair'].includes(j.kind)&&route==='moments')await renderMoments();
   if(!j.automatic&&j.kind!=='emoji')toast(j.kind==='report'?'年度回顾和图片已生成':j.message||'任务已完成');
  }else if(j.status==='error'&&!j.automatic)toast(j.message);
  renderHistory();
 }
 if(modalType==='job')updateJobModal();renderTaskbar();ensureVisibleEmoji();
 const status=$('#privacy-label');if(status)status.innerHTML=icon('lock')+(state.live?.error?'自动更新异常':state.live?.enabled?'本地 · 自动更新':'本地数据');if(status)status.title=state.live?.error||'每秒检查当前账号的新消息';
}catch(err){console.warn('任务状态暂不可用');}finally{polling=false}}
let momentOffset=0;
async function renderMoments(){momentOffset=0;$('#content').innerHTML=`<div class="page">${heading('朋友圈','浏览当前账号已归档的动态；图片会从原动态地址恢复并保存在本机。',btn('同步朋友圈','moments-sync','primary','refresh')+btn('修复半图','moments-repair','','refresh')+btn('从微信界面选择动态','moments-live','','eye')+btn('导出朋友圈','moments-export','','export'))}<div class="search-box"><input id="moments-query" placeholder="搜索文字或作者" aria-label="搜索朋友圈">${btn('搜索','moments-search','small')}</div><div id="moments-feed"></div><div id="moments-more"></div></div>`;await loadMoments(0);}
async function loadMoments(offset){const data=await api('/api/moments?'+new URLSearchParams({q:$('#moments-query')?.value||'',offset,limit:30}));if(route!=='moments')return;const feed=$('#moments-feed');if(!offset)feed.innerHTML='';feed.insertAdjacentHTML('beforeend',data.items.map(m=>MomentRenderer.card(m,asset,true)+`<div class="moment-action-row">${btn('点赞','moment-like','small','',`data-mid="${e(m.id)}"`)}${btn('评论','moment-comment','small','',`data-mid="${e(m.id)}"`)}</div>`).join(''));momentOffset=offset+data.items.length;queueMomentRestore(data.items);if(!data.total)feed.innerHTML=empty('暂无朋友圈归档','点击同步朋友圈，读取当前账号本机缓存的动态。','moments-sync','同步朋友圈','eye');$('#moments-more').innerHTML=momentOffset<data.total?btn(`加载更多 · ${momentOffset} / ${num(data.total)}`,'moments-more','small'):`<p class="muted">共 ${num(data.total)} 条缓存动态</p>`;}
const momentRestoreAttempted=new Set();
async function queueMomentRestore(items){
 const ids=items.filter(m=>(m.detail?.media||[]).some(x=>x.type==='2'&&!x.media_path)&&!momentRestoreAttempted.has(m.id)).map(m=>m.id);
 ids.forEach(id=>momentRestoreAttempted.add(id));
 for(let i=0;i<ids.length;i+=10){
  try{
   const result=await api('/api/moments/restore',{ids:ids.slice(i,i+10)});
   if(route!=='moments')return;
   for(const item of result.updated||[]){
    const button=$(`.moment-card[data-mid="${CSS.escape(item.mid)}"] [data-index="${item.index}"]`);
    const slot=button?.closest('.moment-missing');
    if(slot&&item.media_path){const src=e(asset(item.media_path));slot.outerHTML=`<a href="${src}" target="_blank" rel="noopener"><img src="${src}" loading="lazy" alt="朋友圈图片"></a>`;}else if(slot){const note=slot.querySelector("small");if(note)note.textContent=item.media_status;}
   }
  }catch(err){console.warn('朋友圈图片恢复失败',err);return;}
 }
}
async function browse(kind){const input=kind==='emoji_dir'?$('#listen-emoji-dir'):kind==='data_root'?$('#settings-root'):$('#settings-output')||$('#export-path');if(native)native.chooseFolder(kind,input?.value||'');else{input?.focus();toast('预览模式可直接填写文件夹路径；桌面窗口支持文件夹选择。');}}
const actions={
 ...PersonalUI.actions,
 ...ArticlesUI.actions,
 ...StorageUI.actions,
 'voice-modal':()=>{if(!currentChat||currentChat.kind!=='direct')throw Error('请先选择好友单聊。');modalType='voice';showModal('发送原生微信语音',`<p class="modal-description">请先在电脑版微信中打开“${e(currentChat.title)}”的聊天。录音时会暂时切换键盘焦点到微信，鼠标不会移动；结束后恢复焦点。录制会直接发送给这位好友。</p><label class="field-label">录音时长（秒）<input id="voice-duration" type="number" min="1.5" max="10" step="0.5" value="3"></label><p id="voice-status" role="status"></p>`,btn('开始录音并发送','voice-start','primary','play')+btn('取消','close-modal'));},
 'voice-start':async node=>{const cid=currentChat?.id,duration=Number($('#voice-duration')?.value),accountId=state.selected;if(!cid||!Number.isFinite(duration)||duration<1.5||duration>10)throw Error('请选择 1.5–10 秒录音。');node.disabled=true;const box=$('#voice-status');box.textContent='正在核对微信会话，准备录音…';try{const task=await api('/api/voice/send',{cid,duration});const check=async()=>{try{const job=await api('/api/harness/task/'+encodeURIComponent(task.id));if(accountId!==state.selected)throw Error('账号已切换，请到微信核对语音结果。');if(box?.isConnected)box.textContent=`${job.stage} · ${job.percent}%`;if(job.status==='running'){setTimeout(check,300);return;}if(job.status==='done'){if(box?.isConnected)box.textContent=job.result?.message||'录音操作已完成。';toast(job.result?.message||'语音操作已完成。');}else{if(box?.isConnected)box.textContent=job.error||job.stage;toast(job.error||job.stage);}}catch(err){if(box?.isConnected)box.textContent='状态暂不可用：'+err.message;}};setTimeout(check,300);}catch(err){node.disabled=false;throw err;}},
 'multi-enable':async()=>{await api('/api/weixin/multi',{action:'enable'});await renderMulti();},
 'multi-disable':async()=>{await api('/api/weixin/multi',{action:'disable'});await renderMulti();},
 'multi-launch':async()=>{const job=await api('/api/weixin/multi',{action:'launch'});toast('正在启动新微信窗口…');const check=async()=>{const item=await api('/api/harness/task/'+encodeURIComponent(job.id));if(item.status==='running'){setTimeout(check,500);return;}toast(item.result?.message||item.error||item.stage);};setTimeout(check,500);},
 'send-chat':async node=>{const input=$('#chat-compose-text'),message=input?.value.trim(),cid=currentChat?.id;if(!message)throw Error('请先输入消息。');node.disabled=true;try{const job=await api('/api/automation/send',{cid,message});input.value='';toast('已提交给微信，正在发送…');const check=async()=>{try{const result=await api('/api/automation/send/'+encodeURIComponent(job.id));if(result.status==='running'){setTimeout(check,350);return;}if(result.status==='error'){if(currentChat?.id===cid&&input?.isConnected&&!input.value)input.value=message;toast('发送未确认：'+result.message);}else toast(result.message);}catch(err){toast('发送结果暂不可用，请到微信会话核对。');}if(currentChat?.id===cid&&node.isConnected)node.disabled=false;};setTimeout(check,350);}catch(err){node.disabled=false;throw err;}},
 'retry-media':node=>{const src=node.dataset.src;if(!src?.startsWith('/media/'))throw Error('媒体路径无效。');const box=node.closest('.missing-media');if(box)box.outerHTML=`<a class="image-link" href="${e(src)}" target="_blank" rel="noopener"><img class="message-image" src="${e(src)}?reload=${Date.now()}" alt="重试图片"></a>`;},
 'save-automation':async()=>{const contacts=$$('[data-listen-contact]:checked').map(x=>x.dataset.listenContact);const contact_prompts={},contact_roles={};$$('[data-contact-prompt]').forEach(x=>{if(contacts.includes(x.dataset.contactPrompt)&&x.value.trim())contact_prompts[x.dataset.contactPrompt]=x.value.trim();});$$('[data-contact-role]').forEach(x=>{if(contacts.includes(x.dataset.contactRole)&&x.value)contact_roles[x.dataset.contactRole]=x.value;});const mode=$('input[name="listen-mode"]:checked')?.value||'fixed';const result=await api('/api/automation',{enabled:$('#listen-enabled').checked,contacts,reply:$('#listen-reply').value,mode,role_id:$('#listen-role').value,contact_roles,contact_prompts,context_turns:Number($('#listen-context-inline').value),batch_seconds:Number($('#listen-batch-seconds').value),random_emoji:$('#listen-random-emoji').checked,emoji_dir:$('#listen-emoji-dir').value,emoji_probability:Number($('#listen-emoji-probability').value)});toast(result.enabled?'自动回复已启用':'自动回复已关闭');await renderAutomation();},
 'browse-emoji-dir':()=>browse('emoji_dir'),
 'proactive-prepare':async node=>{const contacts=$$('[data-proactive-contact]:checked').map(x=>x.dataset.proactiveContact),mode=$('input[name="proactive-mode"]:checked')?.value,text=$('#proactive-message').value.trim(),account=state.selected;if(!contacts.length||contacts.length>20)throw Error('请选择 1–20 位好友。');if(!text)throw Error('请填写文字或主题。');node.disabled=true;try{const result=await api('/api/automation/prepare-multi',{contacts,mode,text});if(account!==state.selected)throw Error('登录账号已变化，请重新生成。');proactiveDrafts=result.drafts;proactiveSnapshot=JSON.stringify({account,contacts,mode,text});$('#proactive-preview').innerHTML='<h3>逐条确认草稿</h3>'+proactiveDrafts.map((x,i)=>`<label class="setting-row stack"><b>${e(x.name)}</b><textarea data-proactive-draft="${i}" rows="3" maxlength="2000">${e(x.message)}</textarea></label>`).join('')+`<p class="muted">确认后将按列表顺序操作发送，微信窗口及接口速度会影响完成时间。</p>${btn('确认发送给所选好友','proactive-confirm','primary','arrow')}`;}finally{node.disabled=false;}},
 'proactive-confirm':async node=>{const contacts=$$('[data-proactive-contact]:checked').map(x=>x.dataset.proactiveContact),mode=$('input[name="proactive-mode"]:checked')?.value,text=$('#proactive-message').value.trim();if(proactiveSnapshot!==JSON.stringify({account:state.selected,contacts,mode,text}))throw Error('接收人、账号或内容已变化，请重新生成预览。');const drafts=proactiveDrafts.map((x,i)=>({cid:x.cid,account_id:x.account_id,message:$(`[data-proactive-draft="${i}"]`)?.value.trim()}));if(drafts.some(x=>!x.message))throw Error('每位好友都需要消息内容。');node.disabled=true;try{const result=await api('/api/automation/send-multi',{drafts});const accepted=result.jobs.filter(x=>x.status==='running').length;toast(`已提交 ${accepted} 位好友；${result.jobs.length-accepted} 位未提交。`);const box=$('#proactive-preview');box.innerHTML='<h3>逐人发送状态</h3>'+result.jobs.map((job,i)=>`<p data-send-result="${e(job.id||'')}" class="muted">${e(proactiveDrafts[i]?.name||job.cid)}：${e(job.status==='error'?job.message:'正在发送…')}</p>`).join('');for(const job of result.jobs.filter(x=>x.id)){const line=box.querySelector(`[data-send-result="${CSS.escape(job.id)}"]`);const pollJob=async()=>{try{const current=await api('/api/automation/send/'+encodeURIComponent(job.id));if(current.status==='running'){setTimeout(pollJob,700);return;}if(line?.isConnected)line.textContent=(proactiveDrafts.find(x=>x.cid===job.cid)?.name||job.cid)+'：'+(current.status==='done'?'已操作发送，等待同步确认':current.message);}catch(err){if(line?.isConnected)line.textContent='发送状态暂不可用，请到微信核对。';}};setTimeout(pollJob,700);}proactiveSnapshot='';}finally{node.disabled=false;}},
 'proactive-schedule':async()=>{const contacts=$$('[data-proactive-contact]:checked').map(x=>x.dataset.proactiveContact),mode=$('input[name="proactive-mode"]:checked')?.value,text=$('#proactive-message').value.trim(),due_at=new Date($('#proactive-time').value).getTime()/1000;if(proactiveSnapshot!==JSON.stringify({account:state.selected,contacts,mode,text})||!proactiveDrafts.length)throw Error('请先生成预览。');if(!Number.isFinite(due_at))throw Error('请填写发送时间。');const drafts=proactiveDrafts.map((x,i)=>({cid:x.cid,account_id:x.account_id,message:$(`[data-proactive-draft="${i}"]`)?.value.trim()}));const result=await api('/api/automation/schedule-multi',{drafts,due_at});toast(`已安排 ${result.jobs.length} 位好友的发送计划。`);await renderProactive();},
 'proactive-cancel':async node=>{await api('/api/automation/schedule/cancel',{id:node.dataset.id});toast('已取消');await renderProactive();},
 'proactive-refresh':()=>renderProactive(),
 'insight-style':async node=>{const cid=$('input[name="insight-contact"]:checked')?.value;if(!cid)throw Error('请先选择一位好友。');await runInsightSkill(node,'my_style',cid);},
 'insight-save':async node=>{const cid=insightCid,kind=node.dataset.kind,content=$(`#skill-${kind}`)?.value||'';await api('/api/insights/save-skill',{cid,kind,content});toast('技能规则已保存。');},
 'insight-apply':async node=>{const cid=insightCid,kind=node.dataset.kind,content=$(`#skill-${kind}`)?.value||'';await api('/api/insights/save-skill',{cid,kind,content});await api('/api/insights/apply-skill',{cid,kind});toast('已写入该好友提示词；请到自动回复页选择 AI 模式并启用。');},
 'insight-export':async()=>{if(!insightReport)throw Error('请先生成报告。');const result=await api('/api/insights/export',{report:insightReport});toast('已保存到 '+result.path);},
 'insight-export-skill':async node=>{const result=await api('/api/insights/export-skill',{cid:insightCid,kind:node.dataset.kind});toast('已保存到 '+result.path);},
 'save-model':async()=>{await api('/api/automation',{provider_id:$('#listen-provider').value,api_url:$('#listen-api-url').value,model:$('#listen-model').value,api_key:$('#listen-api-key').value,system_prompt:$('#listen-system').value,time_awareness:$('#listen-time-awareness').checked,image_recognition:$('#listen-image-recognition').checked,emoji_recognition:$('#listen-emoji-recognition').checked});toast('AI 模型设置已保存');await renderModel();},
 'fetch-models':async node=>{node.disabled=true;try{const result=await api('/api/automation/models',{provider_id:$('#listen-provider').value,api_url:$('#listen-api-url').value,api_key:$('#listen-api-key').value});const models=result.models||[];$('#available-models').innerHTML=models.map(id=>`<option value="${e(id)}">${e(id)}</option>`).join('');$('#available-models').hidden=!models.length;$('#model-list-note').textContent=models.length?`已获取 ${models.length} 个模型。点击列表中的名称选用，保存后生效。`:'接口返回的模型列表为空，请手动填写模型名称。';if(models.length===1)$('#listen-model').value=models[0];toast('模型列表已更新');}finally{node.disabled=false;}},
 'choose-model':()=>{const picked=$('#available-models')?.value;if(picked)$('#listen-model').value=picked;},
 'test-model':async node=>{node.disabled=true;const status=$('#model-test-result');status.textContent='正在测试模型连接…';try{const result=await api('/api/automation/test-model',{provider_id:$('#listen-provider').value,api_url:$('#listen-api-url').value,model:$('#listen-model').value,api_key:$('#listen-api-key').value});status.textContent=`连接成功 · ${result.model} · ${result.latency_ms} 毫秒 · 回复：${result.reply}`;}catch(err){status.textContent='连接失败：'+err.message;}finally{if(node.isConnected)node.disabled=false;}},
 'listen-select-all':()=>{const rows=$$('[data-listen-contact]').filter(x=>!x.closest('[data-listen-row]').hidden);const all=rows.length&&rows.every(x=>x.checked);if(!all&&rows.length>100)throw Error('当前筛选结果超过 100 位，请先缩小搜索范围。');rows.forEach(x=>x.checked=!all);$('#listen-count').textContent=`已选择 ${$$('[data-listen-contact]:checked').length} 位`;},
 'proactive-select-all':()=>{const rows=$$('[data-proactive-contact]').filter(x=>!x.closest('[data-proactive-row]').hidden);const all=rows.length&&rows.every(x=>x.checked);if(!all&&rows.length>20)throw Error('当前筛选结果超过 20 位，请先缩小搜索范围。');rows.forEach(x=>x.checked=!all);$('#proactive-count').textContent=`已选择 ${$$('[data-proactive-contact]:checked').length} 位`;},
 'save-media':async()=>{state.settings=await api('/api/settings',{auto_emoji:$('#media-auto-emoji').checked,include_media:$('#media-sync').checked});toast('媒体设置已保存');await renderMedia();},
 'moment-like':async node=>{node.disabled=true;try{const result=await api('/api/automation/moment',{action:'like',mid:node.dataset.mid});toast(result.message||'点赞操作完成');}catch(err){if(err.message.includes('缺少足够'))await showLiveMoments('like');else throw err;}finally{node.disabled=false;}},
 'moment-comment':node=>{momentPicker={mid:node.dataset.mid};modalType='moment-comment';showModal('评论这条朋友圈','<p class="modal-description">将在当前登录的微信界面定位并评论这条动态。作者与全文必须唯一匹配。</p><textarea id="moment-comment-text" rows="4" maxlength="300" style="width:100%" aria-label="评论内容"></textarea>',btn('发送评论','moment-comment-send','primary')+btn('取消','close-modal'));},
 'moment-comment-send':async()=>{const content=$('#moment-comment-text')?.value||'';try{const result=await api('/api/automation/moment',{action:'comment',mid:momentPicker.mid,content});closeModal();toast(result.message||'评论操作完成');}catch(err){if(err.message.includes('缺少足够'))await showLiveMoments('comment',content);else throw err;}},
 'moments-live':()=>showLiveMoments(),
 'moment-live-like':async node=>{const result=await api('/api/automation/moment-live',{action:'like',index:Number(node.dataset.index),fingerprint:node.dataset.fingerprint});closeModal();toast(result.message||'点赞操作完成');},
 'moment-live-comment':async node=>{const content=$('#moment-live-comment')?.value||'';const result=await api('/api/automation/moment-live',{action:'comment',index:Number(node.dataset.index),fingerprint:node.dataset.fingerprint,content});closeModal();toast(result.message||'评论操作完成');},
 'moment-pick':node=>showMomentImages(node.dataset.mid,Number(node.dataset.index)), 'moment-pick-more':()=>showMomentImages(momentPicker.mid,momentPicker.index,momentPicker.offset), 'moment-bind':async node=>{await api('/api/moments/bind',{mid:momentPicker.mid,index:momentPicker.index,asset:node.dataset.asset});const slot=$(`.moment-card[data-mid="${CSS.escape(momentPicker.mid)}"] [data-index="${momentPicker.index}"]`)?.closest('.moment-missing');if(slot)slot.outerHTML=`<a href="${e(asset(node.dataset.asset))}" target="_blank" rel="noopener"><img src="${e(asset(node.dataset.asset))}" alt="用户确认的本机图片"></a>`;closeModal();toast('已使用你确认的本机缓存图片，导出也会包含它');},
 'restore-chat-emoji':()=>startJob('emoji',{message_ids:messages.filter(m=>m.kind==='emoji'&&!m.media_path).map(m=>m.id).slice(-100)}),
 'moments-sync':()=>startJob('moments_sync'),'moments-export':()=>startJob('moments_export',{q:$('#moments-query')?.value||''}),'moments-search':()=>loadMoments(0),'moments-more':()=>loadMoments(momentOffset),'open-report-image':node=>api('/api/open',{job_id:node.dataset.job,image:true}),
 'quit-app':async()=>{if(native?.quitApp)native.quitApp();else toast('请关闭桌面窗口退出软件。');},
 'detect':async()=>{const button=$('[data-action="detect"]');if(button)button.disabled=true;try{state=await api('/api/detect',{});allChats=[];currentChat=null;await loadState();if(modalType==='accounts')accountsModal();else await navigate(route);toast(state.discovery.active_count?'已自动识别当前登录的微信账号':'暂未发现登录账号，可打开已有的离线归档。');}finally{if(button)button.disabled=false;}},
 'accounts':accountsModal,'restore-emoji':()=>startJob('emoji'),'retry-emoji':()=>startJob('emoji',{retry_failed:true}),'go-chat':()=>navigate('chat'),'go-model':()=>navigate('model'),'go-automation':()=>navigate('automation'),'sync':()=>startJob('sync'),'legacy':()=>startJob('legacy'),'go-report':()=>navigate('report'),'older':()=>loadMessages(true),'more-chats':()=>loadConversations(chats.length),
 'moments-repair':()=>startJob('moments_repair'),
 'jump-date':()=>{const value=$('#message-date').value;if(!value)return;const d=new Date(value+'T00:00:00');d.setDate(d.getDate()+1);messageUntil=String(d.getTime()/1000);return loadMessages();},
 'reset-messages':()=>{messageQuery=messageUntil=messageKind='';$('#message-search').value='';$('#message-date').value='';$('#message-kind').value='';return loadMessages();},
 'contacts-prev':()=>{contactsPage=Math.max(0,contactsPage-1);return loadContacts();},'contacts-next':()=>{contactsPage++;return loadContacts();},
 'export-contacts':()=>startJob('export',{formats:['contacts'],contacts:contactSelection.size?[...contactSelection]:null,conversations:[]}),
 'export-emoji':()=>{exportFormats=new Set(['emoji']);return navigate('export');},
 'export-chat':()=>{exportAll=false;exportSelection=new Set([currentChat.id]);return navigate('export');},
 'start-export':async()=>{if(!exportFormats.size)throw Error('请至少选择一种导出格式。');if(!exportAll&&!exportSelection.size&&[...exportFormats].some(f=>f!=='contacts'))throw Error('请至少选择一个会话。');const start=$('#export-start').value,end=$('#export-end').value;let endTs=null;if(end){const d=new Date(end+'T00:00:00');d.setDate(d.getDate()+1);endTs=d.getTime()/1000;}state.settings=await api('/api/settings',{output_dir:$('#export-path').value});await startJob('export',{formats:[...exportFormats],conversations:exportAll?null:[...exportSelection],start:start?new Date(start+'T00:00:00').getTime()/1000:null,end:endTs,include_media:$('#export-media').checked});},
 'generate-report':()=>startJob('report',{year:Number($('#report-year').value),conversation_id:$('#report-contact').value}),
 'antirevoke-status':()=>runAntiRevoke('status'), 'antirevoke-enable':()=>runAntiRevoke('enable'), 'antirevoke-disable':()=>runAntiRevoke('disable'),
 'save-settings':async()=>{state.settings=await api('/api/settings',{output_dir:$('#settings-output').value,data_root:$('#settings-root').value,auto_emoji:$('#settings-auto-emoji').checked,auto_sync:$('#settings-auto').checked,include_media:$('#settings-media').checked,force_keys:$('#settings-keys').checked});toast('设置已保存');},
 'browse-output':()=>browse('output_dir'),'browse-data':()=>browse('data_root'),'close-modal':closeModal,
 'jobs':async()=>{const tasks=(await api('/api/harness/tasks')).items;const latest=state.jobs.at(-1);modalType='harness';showModal('任务中心',`<div class="personal-task-list">${tasks.map(t=>`<div class="panel personal-task"><b>${e(({'personal.memory':'聊天记忆','personal.coach':'表达练习','mirror.analyze':'关系镜像','mirror.skill':'风格提炼','article.call':'本地文章工具','article.download':'文章下载','article.scan':'缓存扫描','weixin.launch':'微信多开','voice.send':'原生语音'})[t.action]||t.action)}</b><span>${e(t.stage)} · ${t.percent}%</span><progress max="100" value="${t.percent}"></progress>${t.error?`<p>${e(t.error)}</p>`:''}${t.status==='running'&&t.action!=='voice.send'?btn('取消','harness-cancel','','close',`data-id="${e(t.id)}"`):['error','cancelled','interrupted'].includes(t.status)&&!['article.call','article.download','weixin.launch','voice.send'].includes(t.action)?btn('继续','harness-resume','','refresh',`data-id="${e(t.id)}"`):''}</div>`).join('')||'<p class="muted">暂无分析或文章任务。</p>'}</div>${latest?`<p class="muted">最近的同步/导出任务：${e(latest.stage||latest.kind)} · ${e(latest.status)}</p>${btn('查看同步或导出详情','job-detail','','arrow',`data-job="${e(latest.id)}"`)} `:''}`);},
 'harness-cancel':async node=>{await api('/api/harness/cancel',{id:node.dataset.id});await actions.jobs();},
 'harness-resume':async node=>{await api('/api/harness/resume',{id:node.dataset.id});await actions.jobs();},
 'job-detail':node=>jobModal(node.dataset.job),'cancel-job':async()=>{await api('/api/cancel',{id:selectedJob});toast('正在取消，原有归档会保留。');},
 'open-job':node=>api('/api/open',{job_id:node.dataset.job}), 'open-report':node=>api('/api/open',{job_id:node.dataset.job,file:true}),
 'share-report':async node=>{const share=await api('/api/share',{job_id:node.dataset.job});modalType='share';showModal('把这一年的回忆，带在身边。',`<div class="qr-content"><img src="${share.qr}" alt="年度回顾二维码"><p>手机与电脑连接同一 Wi-Fi 后扫码查看。<br>只分享这一份年报，链接 30 分钟后失效。<br>关闭此弹窗会立即停止分享。</p><input readonly value="${e(share.url)}" aria-label="年报分享地址"><p>若无法访问，请检查 Windows 是否允许此应用在专用网络中通信。</p></div>`,btn('停止分享','close-modal','primary','lock'));}
};
async function showLiveMoments(prefer='',draft=''){
 const data=await api('/api/automation/moments-live');modalType='moment-live';
 showModal('选择微信界面中的动态',`<p class="modal-description">列出当前微信朋友圈界面可识别的动态。图片或无文字动态可在这里按作者、时间和图片数选择；列表变化时需要刷新后重选。操作会切换微信界面。</p><textarea id="moment-live-comment" rows="2" maxlength="300" style="width:100%" placeholder="评论内容（点赞可留空）">${e(draft)}</textarea><div class="live-moment-list">${data.items.map(x=>`<div class="live-moment-row"><div><b>${e(x.publisher||'未知作者')}</b><small>${e(x.time||'时间未知')} · ${num(x.image_count)} 张图片</small><p>${e(x.text||'无文字动态')}</p></div>${btn('点赞','moment-live-like','small','','data-index="'+x.index+'" data-fingerprint="'+e(x.fingerprint)+'"')}${btn('评论','moment-live-comment','small','','data-index="'+x.index+'" data-fingerprint="'+e(x.fingerprint)+'"')}</div>`).join('')||'<p class="muted">当前微信界面没有可识别的动态。</p>'}</div>`,btn('刷新列表','moments-live','small','refresh')+btn('关闭','close-modal'));
 if(prefer==='comment')$('#moment-live-comment')?.focus();
}
async function renderAutomation(){
 const [cfg,contacts]=await Promise.all([api('/api/automation'),api('/api/contacts?limit=5000')]);
 const people=contacts.items.filter(c=>c.kind==='direct');
 $('#content').innerHTML=`<div class="page">${heading('自动回复','选择好友、回复方式与每人的提示词。',btn('设置 AI 模型','go-model','','spark'))}
 <section class="panel settings-section"><h2>监听与回复规则</h2><p class="muted">仅处理启用后新同步的消息。连续消息按设置合并，不因发送频繁而丢弃；发送状态不确定时不会自动重试。微信发送仍需窗口可交互；后台自动发送会等桌面空闲约 2 秒，完成后尝试恢复原窗口焦点，使用鼠标时不会立即抢操作。</p>
 <label class="setting-row"><span>启用自动回复</span><input id="listen-enabled" type="checkbox" class="switch" ${cfg.enabled?'checked':''}></label>
 <div class="setting-row stack"><span>回复方式</span><div class="choice-row"><label><input type="radio" name="listen-mode" value="fixed" ${cfg.mode==='fixed'?'checked':''}> 固定文字 · 最快</label><label><input type="radio" name="listen-mode" value="ai" ${cfg.mode==='ai'?'checked':''}> AI 模型 · 取决于接口速度</label></div></div>
 <div id="listen-fixed-fields" ${cfg.mode==='ai'?'hidden':''}><div class="setting-row stack"><label for="listen-reply">固定文字</label><textarea id="listen-reply" rows="3" maxlength="500" style="width:100%;margin-top:12px" placeholder="选择固定文字时发送的内容">${e(cfg.reply||'')}</textarea></div></div>
 <div id="listen-ai-fields" ${cfg.mode==='fixed'?'hidden':''}><p class="muted">当前模型：${e(cfg.model)} · ${cfg.provider_id==='ollama'?'本机服务可不填密钥':cfg.has_key?'密钥已加密保存':'当前服务商尚未保存密钥'}${state.live?.error?' · 同步异常：'+e(state.live.error):''}</p><div class="setting-row stack"><label for="listen-role">统一回复角色</label><select id="listen-role">${cfg.roles.map(r=>`<option value="${e(r.id)}" ${cfg.role_id===r.id?'selected':''}>${e(r.name)} · ${e(r.description)}</option>`).join('')}</select><p class="muted">角色决定措辞和处事风格；历史聊天只用来理解上下文，不照抄。下方可为每位好友单独选择。</p><details class="role-library"><summary>查看角色库 · ${cfg.roles.length} 种风格</summary>${cfg.roles.map(r=>`<article><b>${e(r.name)}</b><p>${e(r.details)}</p></article>`).join('')}</details></div><div class="setting-row stack"><label for="listen-context-inline">参考最近几条消息回复</label><input id="listen-context-inline" type="number" min="0" max="10" step="1" value="${num(cfg.context_turns||0)}"><p class="muted">只读取同一好友最近的 0–10 条文字；0 表示只依据新消息。模型和提示词在 AI 模型页配置。</p></div></div>
 <div class="setting-row stack"><label for="listen-batch-seconds">合并消息等待时间（0–20 秒）</label><input id="listen-batch-seconds" type="number" min="0" max="20" step="1" value="${num(cfg.batch_seconds||0)}"><p class="muted">连续消息合并为一次回复；设为 0 时立即处理。持续来信会按批次回复。</p></div>
 <label class="setting-row"><span>随机发送表情图片</span><input id="listen-random-emoji" type="checkbox" class="switch" ${cfg.random_emoji?'checked':''}></label>
 <div class="setting-row stack"><label for="listen-emoji-dir">自备表情图片文件夹</label><div class="setting-path"><input id="listen-emoji-dir" value="${e(cfg.emoji_dir||'')}" placeholder="选择含 GIF、PNG、JPG 的文件夹">${btn('选择文件夹','browse-emoji-dir','','folder')}</div><p class="muted">仅使用你放入此文件夹的图片，发送前先完成文字回复。动态 GIF 在微信中的呈现由微信决定。</p></div>
 <div class="setting-row stack"><label for="listen-emoji-probability">每次回复后发送表情的概率（0–100%）</label><input id="listen-emoji-probability" type="number" min="0" max="100" step="1" value="${num(cfg.emoji_probability??25)}"></div>
 <div class="setting-row stack"><label>选择好友 <span class="muted">最多 100 位；可单选、批量或全选</span></label><div class="setting-path">${btn('全选 / 取消全选','listen-select-all','','check')}<span id="listen-count" class="muted">已选择 ${cfg.contacts.length} 位</span></div><div class="search-box"><input id="listen-search" placeholder="搜索联系人"></div><div id="listen-contacts" class="selection-list" style="max-height:300px">${people.map(c=>`<label class="selection-row" data-listen-row="${e((c.remark||c.nickname||c.username).toLowerCase())}"><input type="checkbox" data-listen-contact="${e(c.username)}" ${cfg.contacts.includes(c.username)?'checked':''}><span>${e(c.remark||c.nickname||c.username)}</span></label>`).join('')}</div></div>
 <div class="setting-row stack" id="listen-prompts" ${cfg.mode==='fixed'?'hidden':''}><label>每位好友的专属角色与要求</label><p class="muted">先勾选好友并保存，再选择风格；专属要求可加入对两人关系的已确认事实。关系镜像生成的成长支持规则也会显示在这里。</p>${people.filter(c=>cfg.contacts.includes(c.username)).map(c=>`<label style="display:block;margin:12px 0">${e(c.remark||c.nickname||c.username)}<select data-contact-role="${e(c.username)}" style="display:block;width:100%;margin-top:6px"><option value="">使用统一角色</option>${cfg.roles.map(r=>`<option value="${e(r.id)}" ${cfg.contact_roles?.[c.username]===r.id?'selected':''}>${e(r.name)}</option>`).join('')}</select><textarea data-contact-prompt="${e(c.username)}" rows="3" maxlength="12000" style="width:100%;margin-top:6px" placeholder="这位好友的专属回复要求（可选）">${e(cfg.contact_prompts?.[c.username]||'')}</textarea></label>`).join('')||'<p class="muted">还没有选中的好友。</p>'}</div>
 <div class="setting-path">${btn('保存并应用','save-automation','primary','check')}</div></section>
 <section class="panel settings-section"><h2>处理记录</h2><div id="listen-events">${cfg.events.slice().reverse().map(x=>`<p class="muted">${e(x.time)} · ${e(x.message)}</p>`).join('')||'<p class="muted">暂无处理记录。</p>'}</div></section></div>`;
 $('#listen-search').addEventListener('input',ev=>{const q=ev.target.value.toLowerCase();$$('[data-listen-row]').forEach(n=>n.hidden=!n.dataset.listenRow.includes(q));});
}
async function renderProactive(){
 const [cfg,contacts]=await Promise.all([api('/api/automation'),api('/api/contacts?limit=5000')]);
 const people=contacts.items.filter(c=>c.kind==='direct');
 const due=new Date(Date.now()+5*60000);due.setMinutes(due.getMinutes()-due.getTimezoneOffset());
 const status={queued:'等待发送',running:'正在发送',done:'已操作发送',uncertain:'结果待确认',cancelled:'已取消'};
 $('#content').innerHTML=`<div class="page">${heading('主动消息','选多位好友，写固定文字或按主题生成各自草稿。',btn('刷新状态','proactive-refresh','','refresh'))}
 <section class="panel settings-section"><h2>选择接收人</h2><p class="muted">最多 20 位；发送前逐条预览和编辑。只有点击确认才会交给微信。</p>
 <div class="setting-path">${btn('全选 / 取消全选','proactive-select-all','','check')}</div><div class="search-box"><input id="proactive-search" placeholder="搜索好友姓名或微信号" aria-label="搜索好友"></div>
 <div class="selection-list" style="max-height:260px">${people.map(c=>`<label class="selection-row" data-proactive-row="${e((c.remark||c.nickname||c.username).toLowerCase())}"><input type="checkbox" data-proactive-contact="${e(c.username)}"><span>${e(c.remark||c.nickname||c.username)}</span></label>`).join('')}</div><p id="proactive-count" class="muted">已选择 0 位</p></section>
 <section class="panel settings-section"><h2>编写内容</h2><div class="choice-row"><label><input type="radio" name="proactive-mode" value="fixed" checked> 固定文字</label><label><input type="radio" name="proactive-mode" value="topic"> AI 主题</label></div>
 <div class="setting-row stack"><label for="proactive-message">文字或主题</label><textarea id="proactive-message" rows="4" maxlength="1000" placeholder="固定文字会用于全部好友；AI 主题会结合各自最近的聊天生成草稿"></textarea></div>
 <div class="setting-path">${btn('生成发送预览','proactive-prepare','primary','arrow')}</div><div id="proactive-preview"></div></section>
 <section class="panel settings-section"><h2>安排一次发送</h2><div class="setting-row stack"><label for="proactive-time">本地时间</label><input id="proactive-time" type="datetime-local" value="${due.toISOString().slice(0,16)}"><p class="muted">先生成固定文字预览，再为选中的好友安排一次发送。程序需保持运行。</p></div><div class="setting-path">${btn('安排已预览的消息','proactive-schedule','','clock')}</div></section>
 <section class="panel settings-section"><h2>发送计划</h2><div class="scheduled-list">${cfg.scheduled.slice().reverse().map(j=>`<div class="setting-row"><div><b>${e(j.name||j.conversation_id)}</b><p>${e(j.message)} · ${e(new Date(j.due_at*1000).toLocaleString('zh-CN'))} · ${status[j.status]||e(j.status)}${j.result?' · '+e(j.result):''}</p></div>${j.status==='queued'?btn('取消','proactive-cancel','small','','data-id="'+e(j.id)+'"'):''}</div>`).join('')||'<p class="muted">还没有发送计划。</p>'}</div></section></div>`;
 proactiveDrafts=[];
 $('#proactive-search').addEventListener('input',ev=>{const q=ev.target.value.toLowerCase();$$('[data-proactive-row]').forEach(n=>n.hidden=!n.dataset.proactiveRow.includes(q));});
}
async function renderModel(){
 const cfg=await api('/api/automation');
 modelProfiles=cfg.providers||{};
 $('#content').innerHTML=`<div class="page">${heading('AI 模型','配置回复接口、统一提示词与视觉识别。',btn('返回自动回复','go-automation','','chat'))}
 <section class="panel settings-section"><h2>模型连接</h2><div class="setting-row stack"><label for="listen-provider">服务商</label><select id="listen-provider">${Object.entries(modelProfiles).map(([id,p])=>`<option value="${e(id)}" ${id===cfg.provider_id?'selected':''}>${e(p.title)}</option>`).join('')}</select><p class="muted">各服务商的地址、模型与密钥分别保存在本机；可切换后继续编辑。</p></div><div class="setting-row stack"><label for="listen-api-url">接口地址</label><div class="setting-path"><input id="listen-api-url" value="${e(cfg.api_url||'https://api.deepseek.com')}" placeholder="https://api.deepseek.com">${btn('测试连接','test-model','','spark')}</div><p class="muted">使用兼容 /chat/completions 的接口。启用 AI 回复时会把选中好友的新消息发送到该地址。</p><p id="model-test-result" class="muted" role="status" aria-live="polite">填好地址、模型和密钥后点击测试；只发送 ping，不读取聊天记录。</p></div>
 <div class="setting-row stack"><label for="listen-model">模型名称</label><div class="setting-path"><input id="listen-model" value="${e(cfg.model||'')}" placeholder="获取列表后选择，或手动填写">${btn('在线获取模型','fetch-models','','refresh')}</div><select id="available-models" size="8" aria-label="可用模型列表" hidden></select><p id="model-list-note" class="muted">点击“在线获取模型”读取当前服务商的可用模型。</p></div>
 <div class="setting-row stack"><label for="listen-api-key">API Key</label><input id="listen-api-key" type="password" autocomplete="new-password" placeholder="${cfg.has_key?'已保存，留空保持不变':'输入 API Key'}"><p class="muted">密钥使用 Windows DPAPI 加密，单独保存在当前用户的本地应用数据目录；分享软件文件不会附带它。</p></div></section>
 <section class="panel settings-section"><h2>AI 回复要求</h2><div class="setting-row stack"><label for="listen-system">统一提示词</label><textarea id="listen-system" rows="4" maxlength="2000" style="width:100%">${e(cfg.system_prompt||'')}</textarea><p class="muted">自动回复页可以给每位好友单独覆盖此提示词。</p></div>
 <label class="setting-row"><span>告诉模型当前本地时间</span><input id="listen-time-awareness" type="checkbox" class="switch" ${cfg.time_awareness?'checked':''}></label>
 </section>
 <section class="panel settings-section"><h2>视觉识别</h2><p class="muted">需要模型支持图片输入。仅使用已恢复到本地归档的图片，单次最多 4 张；尚未恢复的媒体会跳过。</p>
 <label class="setting-row"><span>识别图片</span><input id="listen-image-recognition" type="checkbox" class="switch" ${cfg.image_recognition?'checked':''}></label>
 <label class="setting-row"><span>识别表情包</span><input id="listen-emoji-recognition" type="checkbox" class="switch" ${cfg.emoji_recognition?'checked':''}></label>
 <div class="setting-path">${btn('保存模型设置','save-model','primary','check')}</div></section></div>`;
}
async function renderInsights(){return Mirror.render();}
async function loadInsightSkills(cid){const items=await api('/api/insights/skills?'+new URLSearchParams({cid})),box=$('#insight-skills');if(!box)return;box.innerHTML=['my_style','growth_support'].map(kind=>`<div class="setting-row stack"><label for="skill-${kind}">${kind==='my_style'?'我的聊天风格技能':'成长支持回复技能'}</label><textarea id="skill-${kind}" rows="18" maxlength="12000" placeholder="生成后可在此修改并保存">${e(items[kind]||'')}</textarea><div class="setting-path">${btn('保存技能','insight-save','','check',`data-kind="${kind}"`)}${btn('导出 Markdown','insight-export-skill','','export',`data-kind="${kind}"`)}${btn('应用于已选好友','insight-apply','','arrow',`data-kind="${kind}"`)}</div></div>`).join('');}
async function renderMedia(){
 const health=await api('/api/media/health'),settings=state.settings;
 $('#content').innerHTML=`<div class="page">${heading('媒体管理','检查聊天图片与表情包的本地恢复情况。',btn('同步媒体','sync','primary','refresh'))}
 <div class="stat-grid overview-stats">${statCard('图片消息',num(health.image),'条','file','来自当前账号')}${statCard('表情包消息',num(health.emoji),'条','spark','来自当前账号')}${statCard('可打开媒体',num(health.linked),'条','check','含缩略图与首帧')}${statCard('本机尚无媒体',num(health.unavailable),'条','info','可尝试补全')}</div>
 <section class="panel settings-section"><h2>清晰度与文件检查</h2><p>仅有缩略图：<b>${num(health.thumbnail)}</b> 条；WXGF 可查看首帧：<b>${num(health.first_frame)}</b> 条。</p><p>最近检查 ${num(health.recent_checked)} 个媒体文件，文件缺失 <b>${num(health.recent_broken)}</b> 个。缩略图和首帧可查看，但不能代表原图或完整动画已保存在电脑上。</p></section>
 <section class="panel settings-section"><h2>恢复与导出</h2><label class="setting-row"><span>同步时恢复本机媒体</span><input id="media-sync" type="checkbox" class="switch" ${settings.include_media?'checked':''}></label><label class="setting-row"><span>浏览时自动补全缺失表情</span><input id="media-auto-emoji" type="checkbox" class="switch" ${settings.auto_emoji?'checked':''}></label><div class="setting-path">${btn('保存设置','save-media','primary','check')}${btn('联网补全表情','restore-emoji','','refresh')}${btn('重试失败表情','retry-emoji','','refresh')}${btn('导出表情包','export-emoji','','export')}</div></section></div>`;
}
document.addEventListener('click',async event=>{try{
 const nav=event.target.closest('[data-nav]');if(nav){await navigate(nav.dataset.nav);return;}
 const node=event.target.closest('[data-action]');if(node){if(!node.disabled)await actions[node.dataset.action]?.(node);return;}
 const chat=event.target.closest('[data-chat]');if(chat){await openChat(chat.dataset.chat);return;}
 const filter=event.target.closest('[data-chat-kind]');if(filter){chatKind=filter.dataset.chatKind;$$('[data-chat-kind]').forEach(n=>n.classList.toggle('active',n===filter));await loadConversations();return;}
 const acc=event.target.closest('[data-account-id]');if(acc){state=await api('/api/select',{id:acc.dataset.accountId});allChats=[];currentChat=null;reportJob=null;insightReport=null;insightCid='';Mirror.reset();proactiveDrafts=[];proactiveSnapshot='';contactSelection.clear();exportSelection.clear();exportAll=true;closeModal();await loadState();await navigate('home');return;}
 const ref=event.target.closest('[data-ref]');if(ref){if(!ref.dataset.ref){toast('此归档没有原消息编号。');return;}messageQuery=messageUntil=messageKind='';$('#message-search').value='';$('#message-date').value='';$('#message-kind').value='';await loadMessages(false,ref.dataset.ref);return;}
 const image=event.target.closest('.image-link');if(image){event.preventDefault();modalType='image';showModal('图片预览',`<img class="image-modal" src="${e(image.getAttribute('href'))}" alt="聊天图片">`,'',true);$('#modal .modal-card').classList.add('lightbox-card');return;}
 if(event.target===$('#modal'))closeModal();
}catch(err){toast(err.message);}});
document.addEventListener('error',event=>{const image=event.target;if(!(image instanceof HTMLImageElement)||!image.classList.contains('message-image'))return;const link=image.closest('.image-link'),src=link?.getAttribute('href');if(!link||!src)return;link.outerHTML=`<div class="missing-media"><b>媒体加载失败</b><small>本地文件可能已移动，或格式暂不支持</small>${btn('重新加载','retry-media','small','refresh',`data-src="${e(src)}"`)}</div>`;},true);
document.addEventListener('input',event=>{const t=event.target;clearTimeout(queryTimer);queryTimer=setTimeout(async()=>{try{if(t.id==='chat-search'){chatQuery=t.value;await loadConversations();}else if(t.id==='message-search'){messageQuery=t.value;await loadMessages();}else if(t.id==='contact-search'){contactsQuery=t.value;contactsPage=0;await loadContacts();}else if(t.id==='export-search')renderExportChoices(t.value);}catch(err){toast(err.message);}},200);});
document.addEventListener('change',async event=>{try{const t=event.target;if(t.name==='insight-contact'){insightCid=t.value;insightReport=null;await renderInsights();}else if(t.dataset.proactiveContact){$('#proactive-count').textContent=`已选择 ${$$('[data-proactive-contact]:checked').length} 位`;}else if(t.id==='listen-provider'){const p=modelProfiles[t.value];if(p){$('#listen-api-url').value=p.api_url||'';$('#listen-model').value=p.model||'';$('#listen-api-key').value='';$('#listen-api-key').placeholder=t.value==='ollama'?'本机 Ollama 通常无需密钥':p.has_key?'已保存，留空保持不变':'输入 API Key';$('#available-models').innerHTML='';$('#model-list-note').textContent='切换后点击“在线获取模型”，保存后才会应用。';}}else if(t.id==='report-year'){const year=$('.year-art>span');if(year)year.textContent=t.value;}else if(t.id==='message-kind'){messageKind=t.value;await loadMessages();}else if(t.dataset.format){t.checked?exportFormats.add(t.dataset.format):exportFormats.delete(t.dataset.format);t.closest('.format-card').classList.toggle('selected',t.checked);exportSummary();}else if(t.id==='export-all'){exportAll=t.checked;exportSelection.clear();renderExportChoices($('#export-search').value);}else if(t.dataset.exportChat){if(exportAll){exportAll=false;exportSelection=new Set(allChats.map(c=>c.id));$('#export-all').checked=false;}t.checked?exportSelection.add(t.dataset.exportChat):exportSelection.delete(t.dataset.exportChat);exportSummary();}else if(t.dataset.contact){t.checked?contactSelection.add(t.dataset.contact):contactSelection.delete(t.dataset.contact);$('#contact-count').textContent=`已选择 ${contactSelection.size} 位联系人`;}else if(t.id==='contact-all'){contactRows.forEach(c=>t.checked?contactSelection.add(c.username):contactSelection.delete(c.username));$$('[data-contact]').forEach(n=>n.checked=t.checked);$('#contact-count').textContent=`已选择 ${contactSelection.size} 位联系人`;}}catch(err){toast(err.message);}});
document.addEventListener('change',event=>{const t=event.target;if(t.name==='listen-mode'){$('#listen-fixed-fields').hidden=t.value!=='fixed';$('#listen-ai-fields').hidden=t.value!=='ai';$('#listen-prompts').hidden=t.value!=='ai';}else if(t.dataset.listenContact){$('#listen-count').textContent=`已选择 ${$$('[data-listen-contact]:checked').length} 位`;}else if(t.id==='available-models'){actions['choose-model']();}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();if(event.key==='Enter'&&event.ctrlKey&&event.target.id==='chat-compose-text'){event.preventDefault();actions['send-chat']($('[data-action="send-chat"]')).catch(err=>toast(err.message));return;}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();navigate('chat').then(()=>$('#chat-search')?.focus());}if(event.key==='Tab'&&!$('#modal').classList.contains('hidden')){const nodes=$$('#modal button:not(:disabled),#modal input,#modal a,#modal summary');if(nodes.length){if(event.shiftKey&&document.activeElement===nodes[0]){event.preventDefault();nodes.at(-1).focus();}else if(!event.shiftKey&&document.activeElement===nodes.at(-1)){event.preventDefault();nodes[0].focus();}}}});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1)||'home';if(next!==route)navigate(next).catch(err=>toast(err.message));});
if(window.qt?.webChannelTransport){const script=document.createElement('script');script.src='qrc:///qtwebchannel/qwebchannel.js';script.onload=()=>new QWebChannel(qt.webChannelTransport,channel=>{native=channel.objects.native;native.folderSelected.connect((kind,path)=>{const input=kind==='article_output'?$('#article-output'):kind==='article_cache'?$('#article-cache_root'):kind==='archive_dir'?$('#settings-archive'):kind==='emoji_dir'?$('#listen-emoji-dir'):kind==='data_root'?$('#settings-root'):$('#settings-output')||$('#export-path');if(input)input.value=path;});if(native.yuanbaoSessionChanged)native.yuanbaoSessionChanged.connect(ready=>window.dispatchEvent(new CustomEvent('yuanbao-session',{detail:{ready}})));});document.head.append(script);}
(async()=>{try{await loadState();await navigate(location.hash.slice(1)||'home');setInterval(poll,1000);}catch(err){$('#content').innerHTML=empty('暂时无法打开时光馆',e(err.message),'detect','重新检测');}})();

let momentPicker=null;
async function showMomentImages(mid,index,offset=0){const data=await api('/api/moments/candidates?'+new URLSearchParams({mid,index,offset}));momentPicker={mid,index,offset:offset+data.items.length};modalType='moment-images';showModal('确认朋友圈缓存图片',`<p class="modal-description">以下图片未重绘或二次压缩，但可能是微信保存的缩略缓存。尺寸相同的排在前面，仅供查找，不代表属于这条动态，请核对画面后选择。</p><div class="moment-picker">${data.items.map(x=>`<div><a href="${e(asset(x.asset))}" target="_blank" rel="noopener"><img loading="lazy" src="${e(asset(x.asset))}" alt="本机缓存图片"></a><small>${x.width} × ${x.height}</small>${btn('使用这张图片','moment-bind','small','',`data-asset="${e(x.asset)}"`)}</div>`).join('')||'<p>请先点击同步朋友圈，建立本机图片索引。</p>'}</div>`,(momentPicker.offset<data.total?btn('下一页','moment-pick-more','small'):'')+btn('关闭','close-modal','primary'));}

async function renderMulti(){
 let value,error='';try{value=await api('/api/weixin/multi');}catch(err){error=err.message;}
 $('#content').innerHTML=`<div class="page antirevoke-page">${heading('微信多开','使用当前微信版本对应的多开规则；关闭所有微信进程后写入。',btn('刷新状态','multi-refresh','','refresh'))}<section class="panel settings-section"><h2>${value?`微信 ${e(value.version)}`:'暂时无法识别微信'}</h2><p role="status">${e(error||value.error|| (value.queued?'已预约，等待所有微信进程退出后写入。':value.file_state==='patched'?'多开文件补丁已写入。':'当前尚未安装多开补丁。'))}</p>${value?`<p class="muted">${e(value.path)} · ${value.running?'微信运行中':'微信已退出'}</p><div class="setting-path">${btn('关闭微信后启用多开','multi-enable','primary','check',value.file_state==='patched'?'disabled':'')}${btn('关闭微信后恢复','multi-disable','','refresh',value.file_state==='original'?'disabled':'')}${btn('打开另一个微信','multi-launch','','arrow',value.file_state!=='patched'||value.queued?'disabled':'')}</div>`:''}<p class="muted">补丁应用后重新打开微信，再点击“打开另一个微信”。新窗口需自行登录；每个账号的归档和模型密钥仍按账号分别保存。</p></section></div>`;
}
actions['multi-refresh']=renderMulti;

async function renderAntiRevoke(){
 $('#content').innerHTML=`<div class="page antirevoke-page">${heading('防撤回','关闭微信后应用上游文件补丁。',btn('重新检测','antirevoke-status','','refresh'))}
 <section class="panel settings-section"><div class="section-heading"><h2 id="antirevoke-title">正在检测微信</h2><span class="muted" id="antirevoke-version"></span></div>
 <p id="antirevoke-status" role="status" aria-live="polite">正在识别微信安装文件…</p>
 <div class="setting-row"><div><label>当前微信</label><p id="antirevoke-target">等待检测</p></div></div>
 <div class="setting-row"><div><label>生效验证</label><p>文件写入成功仅代表补丁安装完成。重新打开微信后，请让对方发一条测试消息并撤回，确认消息确实保留。</p></div></div>
 <div class="setting-path">${btn('关闭微信后安装','antirevoke-enable','primary','lock','disabled')}${btn('关闭微信后恢复 / 取消预约','antirevoke-disable','','refresh','disabled')}</div></section>
 <section class="panel settings-section"><h2>使用说明</h2><p>点击安装后，保持拾光运行并正常退出所有微信进程；拾光会先备份原始文件，再应用与当前版本匹配的规则。安装完成后重新打开微信。恢复也需要先退出微信。</p><p>上游完整源码和 GPLv3 许可证已保存在本地；规则来自 <a href="https://github.com/huiyadanli/RevokeMsgPatcher" target="_blank" rel="noopener noreferrer">RevokeMsgPatcher ↗</a>。</p></section></div>`;
 await runAntiRevoke('status');
}
async function runAntiRevoke(action){
 const buttons=$$('[data-action^="antirevoke-"]');buttons.forEach(b=>b.disabled=true);
 const status=$('#antirevoke-status'),title=$('#antirevoke-title');
 if(status)status.textContent='正在检查安装文件与补丁规则…';
 let result=null;
 try{
  result=await api('/api/antirevoke',{action});
  if(status)status.textContent=result.message;
  if(title)title.textContent=result.queued?'等待微信关闭':result.file_state==='patched'?'文件已安装，待撤回实测':'文件可安装';
  const version=$('#antirevoke-version'),target=$('#antirevoke-target');
  if(version)version.textContent=`微信 ${result.version} · 上游规则 ${result.patch_version}`;
  if(target)target.textContent=`${result.running?'微信运行中':'微信已关闭'} · ${result.path}`;
  if(action!=='status')toast(result.message);
 }catch(error){
  if(status)status.textContent=error.message;
  if(title)title.textContent='暂时无法使用';
 }finally{
  buttons.forEach(b=>b.disabled=b.dataset.action==='antirevoke-status'?false:!result|| (b.dataset.action==='antirevoke-enable'?result.file_state==='patched'||result.queued==='patched':result.file_state==='original'&&!result.queued));
 }
}
