'use strict';
window.ArticlesUI=(()=>{
 const modes=[['single','单篇文章','一条链接，保存正文与图片','file'],['links','批量链接','每行一条，去重后依次保存','copy'],['history','历史消息','按公众号分页，支持日期筛选','calendar'],['album','公众号合集','读取合集中的多篇文章','folder'],['channel','视频号视频','粘贴分享链接，保存可用原视频','video']];
 const formats={html:'网页',md:'Markdown',txt:'纯文本',mhtml:'网页快照',docx:'Word',pdf:'PDF',json:'JSON'};
 let mode='single',job='',owner='',timer=0,output='',mcp=null,refreshedScan='';
 const draft={source:'',links:'',keyword:'',start_date:'',end_date:'',max_pages:'0',delay:'1.5',batch_size:'10',retries:'1',cache_root:'',auth:{uin:'',key:'',pass_ticket:'',poc_token:'',poc_sid:''},formats:new Set(['html']),images:true,cover:false,audio:false,video:false,comments:false,skip_existing:true};
 function read(){
  const get=id=>$('#article-'+id)?.value??'';
  for(const key of ['source','links','keyword','start_date','end_date','max_pages','delay','batch_size','retries','cache_root'])if($('#article-'+key))draft[key]=get(key);
  for(const key of Object.keys(draft.auth))if($('#article-auth-'+key))draft.auth[key]=get('auth-'+key);
  for(const key of ['images','cover','audio','video','comments','skip_existing'])if($('#article-'+key))draft[key]=$('#article-'+key).checked;
  if($$('input[name="article-format"]').length)draft.formats=new Set($$('input[name="article-format"]:checked').map(node=>node.value));
  if($('#article-output'))output=get('output');
 }
 const field=(label,id,placeholder='',type='text')=>`<label class="article-field"><span>${label}</span><input id="article-${id}" type="${type}" value="${e(draft[id]||'')}" placeholder="${e(placeholder)}"></label>`;
 const authField=key=>`<label class="article-field"><span>${key}</span><input id="article-auth-${key}" type="password" autocomplete="off" value="${e(draft.auth[key])}" placeholder="仅本次运行使用"></label>`;
 function sourceInput(){return mode==='links'?`<label class="article-field article-wide"><span>文章链接清单 <small>一行一条</small></span><textarea id="article-links" rows="8" placeholder="https://mp.weixin.qq.com/s/...&#10;https://mp.weixin.qq.com/s/..."></textarea></label>`:field(mode==='channel'?'视频号分享链接':mode==='album'?'公众号合集链接':mode==='history'?'公众号文章或主页链接':'微信文章链接','source',mode==='channel'?'https://weixin.qq.com/sph/...':mode==='album'?'https://mp.weixin.qq.com/mp/appmsgalbum?...':'https://mp.weixin.qq.com/s/...','url');}
 function options(){
  if(mode==='channel')return `<section class="article-card article-compact-card"><div class="article-section-title"><span class="article-number">02</span><div><h2>保存位置</h2><p>视频、封面和信息文件会放在同一个文件夹。</p></div></div><div class="article-cache"><label class="article-field article-wide"><span>保存到</span><input id="article-output" value="${e(output)}" placeholder="本地文件夹"></label>${btn('选择文件夹','article-browse-output','','folder')}</div></section>`;
  return `<section class="article-card"><div class="article-section-title"><span class="article-number">02</span><div><h2>保存方式</h2><p>${mode==='single'?'只显示这篇文章可用的保存项目。':'可同时生成多种格式，已存在的文章默认跳过。'}</p></div></div><div class="article-format-grid">${Object.entries(formats).map(([key,label])=>`<label class="article-format"><input type="checkbox" name="article-format" value="${key}" ${draft.formats.has(key)?'checked':''}><span><b>${key.toUpperCase()}</b><small>${label}</small></span></label>`).join('')}</div><div class="article-option-grid">${[['images','正文图片'],['cover','封面'],['audio','音频'],['video','视频'],['comments','获取评论'],['skip_existing','跳过已下载']].map(([key,label])=>`<label class="article-check"><input id="article-${key}" type="checkbox" ${draft[key]?'checked':''}><span>${label}</span></label>`).join('')}</div><div class="article-cache"><label class="article-field article-wide"><span>保存到</span><input id="article-output" value="${e(output)}" placeholder="本地文件夹"></label>${btn('选择文件夹','article-browse-output','','folder')}</div><p class="article-note">HTML 图片使用相对路径，可离线打开。音视频和评论只在原页面提供可访问资源时保存。</p></section>`;
 }
 function advanced(){
  if(mode==='single'||mode==='channel')return '';
  let controls='';let description='';
  if(mode==='links'){controls=field('请求间隔 · 秒','delay','1.5','number')+field('每批链接数','batch_size','10','number')+field('失败重试','retries','1','number');description='按顺序分批处理链接。';}
  else if(mode==='history'){controls=field('标题关键词','keyword','可留空')+field('开始日期','start_date','','date')+field('结束日期','end_date','','date')+field('最多页数','max_pages','0 表示不限','number')+field('请求间隔 · 秒','delay','1.5','number')+field('失败重试','retries','1','number');description='按标题和日期筛选公众号历史文章。';}
  else {controls=field('最多页数','max_pages','0 表示不限','number')+field('请求间隔 · 秒','delay','1.5','number')+field('失败重试','retries','1','number');description='控制合集读取范围和失败重试。';}
  return `<section class="article-card"><div class="article-section-title"><span class="article-number">03</span><div><h2>筛选与节奏</h2><p>${description}</p></div></div><div class="article-fields">${controls}</div></section>`;
 }
 function credentials(status){return mode!=='history'?'':`<section class="article-card"><div class="article-section-title"><span class="article-number">04</span><div><h2>历史消息会话</h2><p>单篇和批量链接无需填写；历史消息使用你自己的有效会话。</p></div></div><div class="article-session-state"><span class="article-led ${status.session_ready?'ready':''}"></span>${status.session_ready?'已在本次运行内存中找到会话参数':'可粘贴会话参数，或扫描你选定的缓存目录'}</div><div class="article-fields">${Object.keys(draft.auth).map(authField).join('')}</div><div class="article-cache"><label class="article-field"><span>自己的微信缓存目录</span><input id="article-cache_root" value="${e(draft.cache_root)}" placeholder="选择目录后扫描近期文件"></label>${btn('选择文件夹','article-browse-cache','','folder')}${btn('扫描缓存','article-scan','','search')}${btn('验证会话','article-verify','','check')}${status.session_ready?btn('清除内存会话','article-clear','','close'):''}</div><p class="article-note">会话参数仅保存在当前程序内存，不写入设置、任务库或日志；关闭软件即失效。</p></section>`;}
 function channelSession(status){return mode!=='channel'?'':`<section class="article-card"><div class="article-section-title"><span class="article-number">03</span><div><h2>视频解析会话</h2><p>官方分享页没有视频流时，使用专用浏览器中的腾讯元宝会话解析。</p></div></div><div class="article-session-state"><span class="article-led ${status.yuanbao_ready?'ready':''}"></span>${status.yuanbao_ready?'已检测到本机登录信息；下载时会再验证':'尚未检测到登录信息，请先登录一次'}</div><div class="article-cache">${btn(status.yuanbao_ready?'打开腾讯元宝':'登录腾讯元宝','article-yuanbao-login',status.yuanbao_ready?'':'primary','user')}</div><p class="article-note">登录信息只保存在当前 Windows 用户的专用浏览器资料夹。接口拒绝会话时会自动取消“已检测”状态，并提示重新登录。</p></section>`;}
 function compatibility(){return mode==='channel'?'':`<details class="article-compat"><summary>兼容现有本地文章工具</summary><p>另一个文章工具已开启 127.0.0.1:4545 MCP 服务时，可沿用它的批量下载与数据导出。</p><div class="article-compat-row">${btn('检测本地工具','article-mcp-status','','refresh')}${btn('获取公众号 ID','article-mcp-id','','search')}${btn('批量下载','article-mcp-batch','','export')}${btn('导出文章数据','article-mcp-export','','file')}</div><p id="article-mcp-state">${mcp?(mcp.connected?'已连接，可用工具 '+mcp.tools.length+' 项':'尚未连接本地工具'):''}</p></details>`;}
 async function render(){
  if(route!=='articles')return;
  if($('#article-source')||$('#article-links'))read();
  clearTimeout(timer);owner=state.selected;
  const status=await api('/api/articles/status');if(!output)output=status.output;
  $('#content').innerHTML=`<div class="page article-page"><div class="article-hero"><div><span class="article-kicker">ARCHIVE / 公众号与视频号</span><h1>把读过的内容，<br><em>好好留在本地。</em></h1><p>下载正文、图片、公众号视频和网页端可用的视频号视频。下载过程和文件都留在你的电脑。</p></div><div class="article-hero-art" aria-hidden="true"><span class="article-sheet sheet-back"></span><span class="article-sheet sheet-front"><i></i><i></i><i></i><i></i></span><span class="article-stamp">收 · 藏</span></div></div><div class="article-layout"><div class="article-main"><section class="article-card"><div class="article-section-title"><span class="article-number">01</span><div><h2>选择内容来源</h2><p>按链接下载，或读取当前有效会话中的历史文章。</p></div></div><div class="article-mode-grid">${modes.map(([key,title,desc,ico])=>`<button class="article-mode ${key===mode?'selected':''}" data-action="article-mode" data-mode="${key}">${icon(ico)}<b>${title}</b><small>${desc}</small></button>`).join('')}</div><div class="article-source">${sourceInput()}</div></section>${options()}${advanced()}${credentials(status)}${channelSession(status)}<div class="article-submit">${btn(mode==='channel'?'下载这个视频':mode==='single'?'下载这篇文章':mode==='history'?'读取并下载历史文章':mode==='album'?'下载这个合集':'开始批量下载','article-download','primary large','arrow')}<span>开始后可在任务中心查看进度，随时停止。</span></div>${compatibility()}</div><aside class="article-aside"><div class="article-guide"><span class="article-guide-label">使用步骤</span><div><b>1</b><p>粘贴链接或选择历史模式</p></div><div><b>2</b><p>选好格式与保存位置</p></div><div><b>3</b><p>打开本地文件查看</p></div></div><div id="article-task" class="article-task-slot"></div><div class="article-side-note">视频号下载以官方网页接口实际返回为准；仅在微信内可播放的内容会明确提示。</div></aside></div></div>`;
  if($('#article-links'))$('#article-links').value=draft.links;
  if(job)poll();
 }
 async function poll(){
  clearTimeout(timer);if(!job||owner!==state.selected||route!=='articles')return;
  const task=await api('/api/harness/task/'+encodeURIComponent(job));const box=$('#article-task');if(!box)return;const result=task.result||{};
  box.innerHTML=`<div class="article-progress"><span class="article-guide-label">${task.status==='running'?'正在处理':'最近一次任务'}</span><strong>${e(task.stage||task.status)}</strong><div class="article-progress-track"><i style="width:${Math.max(0,Math.min(100,Number(task.percent)||0))}%"></i></div><small>${Number(task.percent)||0}% · ${e(task.action==='article.scan'?'缓存扫描':task.action==='article.call'?'本地工具':'内置下载')}</small>${task.error?`<p class="article-error">${e(task.error)}</p>`:''}${result.message?`<p>${e(result.message)}</p>`:''}${typeof result.saved==='number'?`<div class="article-result-count"><b>${num(result.saved)}</b> ${result.kind==='video'?'个视频':'篇文章'}已保存 <span>· ${num(result.failed)} 个失败</span></div>`:''}${result.output?`<div class="article-result-path" title="${e(result.output)}">${e(result.output)}</div>${btn('打开保存目录','article-open','','folder')}`:''}${task.status==='running'?btn('停止任务','article-stop','','close'):''}</div>`;
  if(task.status==='running')timer=setTimeout(()=>poll().catch(err=>toast(err.message)),750);
  else if((task.action==='article.scan'||String(task.error||'').includes('腾讯元宝登录态已失效'))&&refreshedScan!==task.id){refreshedScan=task.id;await render();}
 }
 async function start(kind){
  read();const source=mode==='links'?draft.links:draft.source;if(!source.trim())throw Error('请先填写链接。');if(mode!=='channel'&&!draft.formats.size)throw Error('请至少选择一种导出格式。');
  const task=await api('/api/articles/download',{mode:kind==='verify'?'verify':mode,source,output,formats:[...draft.formats],images:draft.images,cover:draft.cover,audio:draft.audio,video:draft.video,comments:draft.comments,skip_existing:draft.skip_existing,keyword:draft.keyword,start_date:draft.start_date,end_date:draft.end_date,max_pages:draft.max_pages,delay:draft.delay,batch_size:draft.batch_size,retries:draft.retries,auth:draft.auth});
  for(const key of Object.keys(draft.auth))draft.auth[key]='';for(const node of $$('[id^="article-auth-"]'))node.value='';job=task.id;owner=state.selected;await poll();
 }
 async function mcpRun(name){read();if(!mcp?.connected)mcp=await api('/api/articles/mcp-status');if(!mcp.connected)throw Error('本地 MCP 工具未运行。');const task=await api('/api/articles/start',{name,url:draft.source});job=task.id;await poll();}
 const actions={'article-mode':async node=>{read();mode=node.dataset.mode;await render();},'article-download':()=>start('download'),'article-verify':()=>start('verify'),
  'article-browse-output':()=>native?.chooseFolder?native.chooseFolder('article_output',$('#article-output')?.value||''):toast('请直接填写本地输出目录。'),
  'article-browse-cache':()=>native?.chooseFolder?native.chooseFolder('article_cache',$('#article-cache_root')?.value||''):toast('请直接填写微信缓存目录。'),'article-yuanbao-login':()=>native?.loginYuanbao?native.loginYuanbao():toast('请在桌面版拾光中登录腾讯元宝。'),
  'article-scan':async()=>{read();const task=await api('/api/articles/scan',{root:draft.cache_root});job=task.id;await poll();},'article-clear':async()=>{await api('/api/articles/clear-session',{});for(const key of Object.keys(draft.auth))draft.auth[key]='';await render();},'article-stop':async()=>{await api('/api/harness/cancel',{id:job});await poll();},
  'article-open':async()=>{const task=await api('/api/harness/task/'+encodeURIComponent(job));if(task.result?.output&&native?.openLocal)native.openLocal(task.result.output);else toast('保存位置：'+(task.result?.output||'未指定'));},
  'article-mcp-status':async()=>{mcp=await api('/api/articles/mcp-status');$('#article-mcp-state').textContent=mcp.connected?`已连接，可用工具 ${mcp.tools.length} 项`:'本地工具未运行。';},
  'article-mcp-id':()=>mcpRun('get_public_account_id'),'article-mcp-batch':()=>mcpRun('batch_download_articles'),'article-mcp-export':()=>mcpRun('export_article_data')};
 return {render,actions};
})();
window.addEventListener('yuanbao-session',()=>{if(route==='articles')ArticlesUI.render().catch(err=>toast(err.message));});
