'use strict';
// Relationship Mirror keeps temporary upload text in memory. Model requests only follow a button click.
const Mirror=(()=>{
 let source='local',mode='both',uploadText='',uploadPreview=null,selfLabel='',practice=[],generation=0,loadedCid='',rangeStart='',rangeEnd='';
 const safe=x=>e(String(x??''));
 const selected=()=>document.querySelector('input[name="insight-contact"]:checked')?.value||insightCid;
 const reportForSelection=()=>insightReport&&insightReport.mode===mode&&((source==='local'&&insightReport.conversation?.id===insightCid)||(source==='upload'&&selfLabel&&insightReport.conversation?.id===uploadPreview?.conversation?.id));
 const refs=(ids,report)=>{const valid=new Set((report.evidence||[]).map(x=>x.id));return (ids||[]).filter(id=>valid.has(id)).map(id=>`<a href="#mirror-evidence-${safe(id)}" class="mirror-ref" aria-label="查看证据 ${safe(id)}">${safe(id)}</a>`).join(' ');};
 const item=(x,report)=>typeof x==='string'?`<li>${safe(x)}</li>`:`<li>${x.dimension?`<b>${safe(x.dimension)}：</b>`:''}${safe(x.observation||x.behavior||x.text||'观察')} ${x.confidence?`<span class="mirror-confidence">证据${safe(x.confidence)}</span>`:''}${refs(x.refs,report)}${x.alternate?`<p class="muted">其他解释：${safe(x.alternate)}</p>`:''}</li>`;
 const list=(a,report)=>`<ul class="mirror-list">${(a||[]).map(x=>item(x,report)).join('')||'<li class="muted">样本不足，暂不推断。</li>'}</ul>`;
 const field=(label,value)=>value?`<p><b>${label}：</b>${safe(value)}</p>`:'';
 function renderProfile(profile,report){if(!profile)return '<p class="muted">仅看自己的模式下，这里只保留互动上下文，不评价对方。</p>';return `<h3>可见的沟通表现</h3>${list(profile.strengths,report)}<h3>五个情境倾向</h3>${list(profile.tendencies,report)}${field('情绪中的表现',profile.emotion)}${field('沟通方式',profile.communication)}${refs(profile.summary_refs,report)}`;}
 function renderReport(report){const s=report.sections||{},range=`${safe(report.from_time||'起点未知')} 至 ${safe(report.to_time||'终点未知')}`;
  const changes=(s.changes||[]).slice(0,3).map((x,i)=>`<article class="mirror-change"><h3>${i+1}. ${safe(x.behavior)}</h3>${field('常见触发',x.trigger)}${field('旧行为',x.old_behavior)}${field('可试的新行为',x.new_behavior)}${field('可以这样说',x.example)}${refs(x.refs,report)}<details><summary>展开改变卡片</summary><div class="mirror-card">${field('触发',x.trigger)}${field('旧行为',x.old_behavior)}${field('短期收获',x.card?.short_gain)}${field('长期代价',x.card?.long_cost)}${field('支持证据参考',x.card?.supporting_evidence)}${field('反面证据参考',x.card?.counter_evidence)}${field('替代想法参考',x.card?.alternate_thought)}<label>当时的自动想法和情绪（由你填写）<textarea data-mirror-reflection="${i}" rows="3" placeholder="我当时想到……，感到……"></textarea></label><label>支持这个想法的证据和反证（由你填写）<textarea data-mirror-evidence-note="${i}" rows="3" placeholder="支持：……；反证：……"></textarea></label><label>尝试新行为后的感受（由你填写）<textarea data-mirror-new-feeling="${i}" rows="2"></textarea></label>${field('新行为',x.new_behavior)}${field('例句',x.example)}${s.plan?.length?btn('带入今日练习','mirror-card-to-practice','','arrow',`data-index="${i}"`):''}</div></details></article>`).join('');
  const phases=['第 1 阶段 · 观察','第 2 阶段 · 暂停','第 3 阶段 · 尝试','第 4 阶段 · 复盘'];
  const plan=(s.plan||[]).map((x,i)=>`<div class="mirror-day"><span>第 ${safe(x.day||i+1)} 天 · ${safe(x.phase||phases[Math.min(3,Math.floor(i/7))])}</span><p>${safe(x.task)}</p>${practice.some(y=>Number(y.day)===Number(x.day))?'<small>已填写练习记录</small>':''}</div>`).join('');
  return `<div class="mirror-report"><div class="mirror-scope"><b>${safe(report.conversation?.title||'上传聊天')}</b><span>${safe(report.mode==='self'?'仅看自己的模式':'双人互动模式')} · ${report.sampled===report.total?'全量':'抽样'} ${num(report.sampled)} / ${num(report.total)} 条 · ${range}</span></div>${(report.warnings||[]).map(x=>`<p class="mirror-warning">${safe(x)}</p>`).join('')}<p class="muted">${report.sampled===report.total?'已把所选范围内的文字全部纳入分析':'此报告基于早期抽样'}；结论只保留可回看原文的证据。高、中、低表示证据充分程度。</p>
  <section class="mirror-module"><span class="mirror-number">01</span><h2>我：沟通中的优势和习惯</h2>${renderProfile(s.self,report)}</section>
  <section class="mirror-module"><span class="mirror-number">02</span><h2>${report.mode==='self'?'对方：互动上下文':'对方：可见的沟通表现'}</h2>${renderProfile(s.other,report)}</section>
  <section class="mirror-module"><span class="mirror-number">03</span><h2>我们的互动循环</h2>${(s.events||[]).map(x=>`<div class="mirror-event">${field('触发',x.trigger)}${field('我的反应',x.a_behavior)}${field('对方的反应',x.b_behavior)}${field('可能的需要',x.possible_needs)}${refs(x.refs,report)}</div>`).join('')}${s.cycle?.name||s.cycle?.steps?.length?`<div class="mirror-cycle"><b>${safe(s.cycle.name)}</b><div class="mirror-steps">${(s.cycle.steps||[]).map((x,i)=>`<span>${safe(x)}</span>`).join('<span aria-hidden="true">→</span>')}</div>${refs(s.cycle.refs,report)}${field('其他解释',s.cycle.alternate)}</div>`:'<p class="muted">目前还看不出可靠的重复循环，可以在更多聊天记录中继续观察。</p>'}</section>
  <section class="mirror-module"><span class="mirror-number">04</span><h2>最值得先改变的 1–3 个行为</h2>${(s.changes||[]).length?list((s.changes||[]).slice(0,3),report):'<p class="muted">没有足够依据推荐具体行为。</p>'}</section>
  <section class="mirror-module"><span class="mirror-number">05</span><h2>改变卡片</h2><p class="muted">填写后可带入当天练习，再由你点击保存。</p>${changes||'<p class="muted">等观察到具体的可改变行为后，再使用改变卡片。</p>'}</section>
  <section class="mirror-module"><span class="mirror-number">06</span><h2>30 天小练习</h2><p class="muted">四阶段逐步练习。完成当天任务后，自己填写记录；系统不会自动判定成长。</p>${plan?`<div class="mirror-plan">${plan}</div>`:'<p class="muted">当前样本不足以制定具体练习，请补充聊天记录后再生成。</p>'}${plan?`<div class="mirror-practice"><label>选择练习日<select id="mirror-practice-day">${(s.plan||[]).map(x=>`<option value="${safe(x.day)}">第 ${safe(x.day)} 天 · ${safe(x.task)}</option>`).join('')}</select></label><label>今天做了什么<textarea id="mirror-practice-note" rows="2"></textarea></label><label>原本想怎么回应<textarea id="mirror-practice-old" rows="2"></textarea></label><label>实际的新回应<textarea id="mirror-practice-new" rows="2"></textarea></label><label>改变前的情绪<textarea id="mirror-practice-emotion-before" rows="2"></textarea></label><label>改变后的情绪<textarea id="mirror-practice-emotion-after" rows="2"></textarea></label><label>结果与复盘<textarea id="mirror-practice-outcome" rows="2"></textarea></label>${btn('保存这一天的练习','mirror-practice-save','primary','check')}</div>`:''}</section>
  ${(report.deep_sections||[]).length?`<section class="mirror-module"><span class="mirror-number">07</span><h2>深度观察 · 证据与替代解释</h2><p class="muted">以下主题仅依据本报告已核对的聊天证据；缺失的方面会明确写出证据不足。</p>${report.deep_sections.map(x=>`<details class="mirror-depth"><summary>${safe(x.title)}</summary><p>${safe(x.text)}</p>${refs(x.refs,report)}${x.limits?`<p class="muted">局限与其他解释：${safe(x.limits)}</p>`:''}</details>`).join('')}</section>`:''}
  <details class="mirror-evidence"><summary>查看引用原文（${num((report.evidence||[]).length)} 条）</summary>${(report.evidence||[]).map(x=>`<p id="mirror-evidence-${safe(x.id)}"><b>${safe(x.id)}</b> · ${safe(x.time)} · ${safe(x.side)}：${safe(x.text)}</p>`).join('')}</details><div class="setting-path">${btn('保存 HTML 报告','insight-export','','export')}${source==='local'?btn('生成成长支持技能','insight-growth','','spark'):''}</div></div>`;
 }
 async function loadSaved(cid,token,origin=source){try{const [saved,records]=await Promise.all([api('/api/insights/saved?'+new URLSearchParams({cid})),api('/api/insights/practice?'+new URLSearchParams({cid}))]);if(token!==generation||source!==origin||route!=='insights'||(origin==='local'?insightCid!==cid:uploadPreview?.conversation?.id!==cid))return;insightReport=saved?.sections?saved:null;practice=records.items||[];if(insightReport)mode=insightReport.mode||mode;await render();}catch(err){if(token===generation)toast(err.message);}}
 async function render(){const token=++generation;const people=stats?(await api('/api/contacts?limit=5000')).items.filter(c=>c.kind==='direct'):[];if(token!==generation||route!=='insights')return;
  document.querySelector('#content').innerHTML=`<div class="page mirror-page">${heading('关系镜像','从聊天记录中发现你的沟通模式、关系循环和可改变行为。')}
  <section class="panel settings-section"><h2>选择聊天来源</h2><div class="choice-row"><label><input type="radio" name="mirror-source" value="local" ${source==='local'?'checked':''}> 本地好友聊天</label><label><input type="radio" name="mirror-source" value="upload" ${source==='upload'?'checked':''}> 上传或粘贴两人聊天</label></div><div id="mirror-local" ${source==='upload'?'hidden':''}><div class="search-box"><input id="insight-search" placeholder="搜索好友姓名或微信号" aria-label="搜索好友"></div><div class="selection-list mirror-contacts">${people.map(c=>`<label class="selection-row" data-insight-row="${safe((c.remark||c.nickname||c.username).toLowerCase())}"><input type="radio" name="insight-contact" value="${safe(c.username)}" ${insightCid===c.username?'checked':''}><span>${safe(c.remark||c.nickname||c.username)}</span></label>`).join('')}</div><div class="choice-row"><label>开始日期 <input id="mirror-start" type="date" value="${safe(rangeStart)}"></label><label>结束日期 <input id="mirror-end" type="date" value="${safe(rangeEnd)}"></label></div><p class="muted">两项都留空则分析整段聊天；填写日期则分析该时间段内全部文字。范围越大，模型请求越多。</p></div><div id="mirror-upload" ${source==='local'?'hidden':''}><label class="mirror-field">选择 TXT 或 Markdown 聊天文本<input id="mirror-file" type="file" accept=".txt,.text,.md,text/plain"></label><label class="mirror-field">或粘贴聊天文本<textarea id="mirror-upload-text" rows="6" placeholder="A：你好\nB：你好">${safe(uploadText)}</textarea></label><p class="muted">每条消息单独一行，使用“A：文字”“B：文字”；至少 4 条，双方都有发言。</p>${btn('解析并预览','mirror-preview','','eye')}<div id="mirror-preview-box">${uploadPreview?previewHtml(uploadPreview):''}</div></div><p class="muted">只有明确点击“生成关系镜像”或“表达检查”才会调用在线模型。不做人格或疾病标签判断。</p><div class="choice-row"><label><input type="radio" name="mirror-mode" value="both" ${mode==='both'?'checked':''}> 看双方互动</label><label><input type="radio" name="mirror-mode" value="self" ${mode==='self'?'checked':''}> 仅看自己的模式</label></div><div class="setting-path">${btn('生成关系镜像','mirror-analyze','primary','spark')}</div></section>
  <section class="panel settings-section"><h2>关系镜像报告</h2><div id="insight-report">${reportForSelection()?renderReport(insightReport):'<p class="muted">选择好友，或上传并预览两人聊天，再点击生成。每条结论可回看引用原文。</p>'}</div></section>
  <section class="panel settings-section"><h2>我的聊天风格与成长支持</h2><p class="muted">风格规则只参考你发出的文字。两种技能都可以编辑、保存和导出；应用后也不会在这里启用发送。</p>${source==='local'?`<div class="setting-path">${btn('提炼我的回复风格','insight-style','','spark')}</div><div id="insight-skills"></div>`:'<p class="muted">技能需要选择本地好友聊天。</p>'}</section></div>`;
  document.querySelector('[data-action="mirror-analyze"]')?.closest('.setting-path')?.insertAdjacentHTML('afterend','<div id="mirror-progress" role="status" aria-live="polite" hidden><progress id="mirror-progress-bar" max="100" value="0"></progress> <span id="mirror-progress-label">准备分析</span></div>');
  document.querySelector('#mirror-start')?.closest('.choice-row')?.insertAdjacentHTML('beforeend',btn('整段聊天','mirror-all','','refresh'));
  document.querySelector('#insight-search')?.addEventListener('input',ev=>{const q=ev.target.value.toLowerCase();document.querySelectorAll('[data-insight-row]').forEach(n=>n.hidden=!n.dataset.insightRow.includes(q));});
  if(source==='local'&&insightCid){try{const range=await api('/api/insights/range?'+new URLSearchParams({cid:insightCid}));if(token===generation&&route==='insights'){
    for(const input of [document.querySelector('#mirror-start'),document.querySelector('#mirror-end')]){if(input){input.min=range.first;input.max=range.last;if(input.value&&(input.value<range.first||input.value>range.last))input.value='';}}
    const note=document.querySelector('#mirror-start')?.closest('.choice-row')?.nextElementSibling;if(note)note.textContent=range.count?`该好友有 ${num(range.count)} 条文字，日期 ${range.first} 至 ${range.last}。点击日期打开日历；留空或点“整段聊天”分析全部。`:'这位好友暂无可分析的聊天文字。';
  }}catch(err){if(token===generation)toast(err.message);}try{await loadInsightSkills(insightCid);}catch(err){if(token===generation)toast(err.message);}if(loadedCid!==insightCid){loadedCid=insightCid;loadSaved(insightCid,generation);}}
 }
 function previewHtml(data){return `<div class="mirror-preview"><h3>解析预览</h3><p class="muted">识别到 ${num(data.total)} 条；${safe(data.from_time)} 至 ${safe(data.to_time)}。核对以下样本，再选哪位是你。</p>${(data.warnings||[]).map(x=>`<p class="mirror-warning">${safe(x)}</p>`).join('')}<div class="mirror-preview-lines">${(data.evidence||[]).slice(0,10).map(x=>`<p><b>${safe(x.side)}</b> · ${safe(x.time)}：${safe(x.text)}</p>`).join('')}</div><fieldset><legend>哪位是你？</legend><label><input type="radio" name="mirror-self" value="A" ${selfLabel==='A'?'checked':''}> A</label><label><input type="radio" name="mirror-self" value="B" ${selfLabel==='B'?'checked':''}> B</label></fieldset></div>`;}
 function reset(){source='local';mode='both';rangeStart='';rangeEnd='';uploadText='';uploadPreview=null;selfLabel='';practice=[];loadedCid='';generation++;}
 function attachComposer(c){if(c.kind!=='direct')return;const input=document.querySelector('#chat-compose-text');if(!input)return;input.insertAdjacentHTML('afterend',`<button class="btn small" data-action="mirror-preflight">${icon('spark')}表达检查</button>`);input.closest('.chat-compose')?.insertAdjacentHTML('afterend','<div id="mirror-preflight-result" class="preflight-result" hidden></div>');input.addEventListener('input',()=>{const box=document.querySelector('#mirror-preflight-result');if(box)box.hidden=true;});}
 async function preview(node){uploadText=document.querySelector('#mirror-upload-text')?.value.trim()||'';if(!uploadText)throw Error('请先粘贴或选择两人聊天文本。');const request=++generation,text=uploadText;node.disabled=true;try{const data=await api('/api/insights/preview-upload',{text});if(request!==generation||source!=='upload'||uploadText!==text)return;uploadPreview=data;selfLabel='';insightReport=null;practice=[];document.querySelector('#mirror-preview-box').innerHTML=previewHtml(data);}finally{if(node.isConnected)node.disabled=false;}}
 async function analyze(node){const cid=selected();if(source==='local'&&!cid)throw Error('请先选择一位好友。');if(source==='upload'&&(!uploadPreview||!selfLabel))throw Error('请先解析预览，并确认哪位是你。');rangeStart=document.querySelector('#mirror-start')?.value||'';rangeEnd=document.querySelector('#mirror-end')?.value||'';if(rangeStart&&rangeEnd&&rangeStart>rangeEnd)throw Error('结束日期不能早于开始日期。');const accountId=state.selected,request=++generation,chosenSource=source,chosenMode=mode,chosenCid=cid;node.disabled=true;const box=document.querySelector('#mirror-progress');box.hidden=false;let stage='读取全部文字',percent=0;const startedAt=Date.now(),ticker=setInterval(()=>{const label=document.querySelector('#mirror-progress-label');if(label&&request===generation)label.textContent=`${stage} · ${percent}% · 已用 ${Math.floor((Date.now()-startedAt)/1000)} 秒`;},1000);toast('正在分析聊天，请查看进度…');try{const start=rangeStart?new Date(rangeStart+'T00:00:00').getTime()/1000:null,end=rangeEnd?new Date(rangeEnd+'T00:00:00').getTime()/1000+86400:null;const body=source==='local'?{cid,mode,start,end}:{upload:{text:uploadText,self_label:selfLabel},mode};const started=await api('/api/insights/analysis/start',body);for(;;){if(request!==generation||route!=='insights'||accountId!==state.selected||chosenSource!==source||chosenMode!==mode||chosenCid!==selected())return;const job=await api('/api/insights/analysis/'+encodeURIComponent(started.id));stage=job.stage;percent=job.percent;const bar=document.querySelector('#mirror-progress-bar');if(bar)bar.value=percent;if(job.status==='error')throw Error(job.error||'关系镜像分析失败。');if(job.status==='done'){insightReport=job.report;await render();return;}await new Promise(resolve=>setTimeout(resolve,800));}}finally{clearInterval(ticker);if(node.isConnected)node.disabled=false;}}
 function preflight(){const input=document.querySelector('#chat-compose-text'),text=input?.value.trim();if(!text)throw Error('请先输入草稿。');if(currentChat?.kind!=='direct')throw Error('表达检查仅支持好友聊天。');const box=document.querySelector('#mirror-preflight-result');box.hidden=false;box.innerHTML=`<h3>表达检查</h3><label>我真正想表达的需求（可选）<textarea id="mirror-need" rows="2" placeholder="例如：我希望对方知道我需要提前商量时间"></textarea></label><p class="muted">只分析当前草稿与这里填写的需求。由你决定是否使用改写。</p>${btn('检查这段草稿','mirror-preflight-run','primary','spark')}`;}
 async function preflightRun(node){const input=document.querySelector('#chat-compose-text'),text=input?.value.trim(),need=document.querySelector('#mirror-need')?.value.trim()||'',cid=currentChat?.id,accountId=state.selected;if(!text)throw Error('请先输入草稿。');node.disabled=true;try{const result=await api('/api/insights/preflight',{cid,text,need});if(route!=='chat'||currentChat?.id!==cid||state.selected!==accountId||input?.value.trim()!==text)return;const box=document.querySelector('#mirror-preflight-result');if(!box)return;box.hidden=false;box.innerHTML=`<h3>表达检查</h3><p><b>可能的误解：</b>${safe(result.possible_reading||'未发现明显歧义')}</p><p><b>需求确认：</b>${safe(result.need_question||need||'请确认自己最想让对方知道什么。')}</p>${(result.signals||[]).map(x=>`<p>${safe(x.label)}</p>`).join('')}<label>可编辑的改写<textarea id="mirror-rewrite" rows="3">${safe(result.rewrite||text)}</textarea></label><p class="muted">${safe(result.limitations||'仅供你参考；发送前由你决定。')}</p>${btn('替换草稿','mirror-replace','','check')}`;}finally{if(node.isConnected)node.disabled=false;}}
 async function savePractice(node){const cid=insightReport?.conversation?.id,report_id=insightReport?.id,accountId=state.selected,day=Number(document.querySelector('#mirror-practice-day')?.value),note=document.querySelector('#mirror-practice-note')?.value.trim(),old_response=document.querySelector('#mirror-practice-old')?.value.trim(),new_response=document.querySelector('#mirror-practice-new')?.value.trim(),outcome=document.querySelector('#mirror-practice-outcome')?.value.trim(),emotion_before=document.querySelector('#mirror-practice-emotion-before')?.value.trim(),emotion_after=document.querySelector('#mirror-practice-emotion-after')?.value.trim();if(!note&&!old_response&&!new_response&&!outcome&&!emotion_before&&!emotion_after)throw Error('请填写当天练习记录。');node.disabled=true;try{const result=await api('/api/insights/practice',{cid,report_id,day,note,old_response,new_response,outcome,emotion_before,emotion_after});if(route!=='insights'||!reportForSelection()||state.selected!==accountId||insightReport?.id!==report_id)return;practice=result.items||[];await render();toast('练习记录已保存。');}finally{if(node.isConnected)node.disabled=false;}}
 function install(){Object.assign(actions,{'mirror-all':()=>{rangeStart='';rangeEnd='';const first=document.querySelector('#mirror-start'),last=document.querySelector('#mirror-end');if(first)first.value='';if(last)last.value='';},'mirror-preview':preview,'mirror-analyze':analyze,'mirror-preflight':preflight,'mirror-preflight-run':preflightRun,'mirror-replace':()=>{const value=document.querySelector('#mirror-rewrite')?.value||'',input=document.querySelector('#chat-compose-text');if(input){input.value=value;input.focus();document.querySelector('#mirror-preflight-result').hidden=true;}},'mirror-card-to-practice':node=>{const i=Number(node.dataset.index),change=insightReport?.sections?.changes?.[i];if(!change)return;const reflection=document.querySelector(`[data-mirror-reflection="${i}"]`)?.value||'',evidence=document.querySelector(`[data-mirror-evidence-note="${i}"]`)?.value||'',feeling=document.querySelector(`[data-mirror-new-feeling="${i}"]`)?.value||'';document.querySelector('#mirror-practice-note').value=[change.behavior,reflection].filter(Boolean).join('\n');document.querySelector('#mirror-practice-old').value=change.old_behavior||'';document.querySelector('#mirror-practice-new').value=change.new_behavior||'';document.querySelector('#mirror-practice-outcome').value=evidence;document.querySelector('#mirror-practice-emotion-after').value=feeling;document.querySelector('.mirror-practice')?.scrollIntoView({block:'center',behavior:'smooth'});toast('已带入练习表，请核对并点击保存。');},'mirror-practice-save':savePractice,'insight-export':async()=>{if(!insightReport)throw Error('请先生成报告。');const result=await api('/api/insights/export',{report:insightReport});toast('已保存到 '+result.path);},'insight-growth':async node=>{if(source!=='local'||!insightReport||insightReport.conversation?.id!==insightCid)throw Error('请先生成该好友的报告。');await runInsightSkill(node,'growth_support',insightCid);}});
  document.addEventListener('change',async ev=>{const t=ev.target;if(t.name==='mirror-source'){source=t.value;insightReport=null;generation++;await render();}else if(t.name==='mirror-mode'){mode=t.value;insightReport=null;generation++;await render();}else if(t.name==='mirror-self'){selfLabel=t.value;insightReport=null;practice=[];const request=++generation,text=uploadText,label=selfLabel;try{const data=await api('/api/insights/preview-upload',{text,self_label:label});if(request!==generation||source!=='upload'||selfLabel!==label||uploadText!==text)return;uploadPreview=data;await render();loadSaved(data.conversation.id,generation,'upload');}catch(err){toast(err.message);}}else if(t.id==='mirror-file'){const file=t.files?.[0];if(file){if(file.size>2_000_000){toast('文件超过 2 MB，请先裁剪文本。');return;}const request=++generation;uploadPreview=null;selfLabel='';insightReport=null;practice=[];uploadText=await file.text();if(request!==generation||source!=='upload')return;const area=document.querySelector('#mirror-upload-text');if(area)area.value=uploadText;}}},true);
  document.addEventListener('input',ev=>{if(ev.target.id==='mirror-upload-text'){uploadText=ev.target.value;uploadPreview=null;selfLabel='';insightReport=null;practice=[];generation++;const box=document.querySelector('#mirror-preview-box');if(box)box.innerHTML='';}},true);
  document.addEventListener('click',ev=>{const ref=ev.target.closest('.mirror-ref');if(ref){ev.preventDefault();const details=document.querySelector('.mirror-evidence');if(details)details.open=true;setTimeout(()=>document.querySelector(ref.getAttribute('href'))?.scrollIntoView({block:'center'}),0);}},true);
 }
 document.addEventListener('DOMContentLoaded',install);
 return {render,reset,attachComposer};
})();
